// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
const __sa_live = new Set(); // live heap bases (user pointers handed out by __sa_alloc)
const __sa_fl = Object.create(null); // free-list buckets: aligned size -> stack of user pointers
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((__sa_num(size) | 0), 8);
  const bucket = __sa_fl[size];
  if (bucket && bucket.length) { const ptr = bucket.pop(); __sa_u8.fill(0, ptr, ptr + size); __sa_live.add(ptr | 0); return ptr | 0; }
  const total = (size + 8); // 8-byte header holds the aligned user size
  const base = __sa_brk;
  __sa_brk += total;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, base, base + total);
  __sa_view.setUint32(base, size, true);
  const ptr = (base + 8);
  __sa_live.add(ptr | 0);
  return ptr | 0;
}
function __sa_free(ptr) {
  // Mirrors the interpreter: only exact live heap bases are recycled.
  // BigInt pointers are normalized to 32-bit addresses first so
  // 64-bit-typed bases stay freeable; interior pointers, consts and
  // unknown addresses remain no-ops (never present in __sa_live).
  const p = __sa_addr(ptr);
  if (!__sa_live.has(p)) return 0;
  __sa_live.delete(p);
  const size = __sa_view.getUint32((p - 8), true);
  (__sa_fl[size] || (__sa_fl[size] = [])).push(p);
  return 0;
}
const __sa_fstack = []; // call-stack of frames; each frame lists its stack slots
function __sa_salloc(size) {
  // Function-scoped allocation: freed when the owning frame returns
  // (mirrors stack-slot lifetime; the interpreter never frees these
  // mid-frame either). Returned to the free list on frame pop.
  const ptr = __sa_alloc(size);
  if (__sa_fstack.length) __sa_fstack[__sa_fstack.length - 1].push(ptr | 0);
  return ptr;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), __sa_narrow(v, 8, true)); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), __sa_narrow(v, 8, false)); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), __sa_narrow(v, 16, true), true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), __sa_narrow(v, 16, false), true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), __sa_narrow(v, 32, true), true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), __sa_narrow(v, 32, false), true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a)) / d; } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a)) % d; } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_narrow(v, bits, signed) {
  // Narrow any int-domain value to a target width, returned as Number.
  // BigInt inputs are 64-bit sources; Number inputs are 32-bit (or
  // smaller) sources. Matches interpreter wrap-around for
  // trunc/zext/sext/bitcast to widths <= 32.
  if (typeof v === "bigint") return signed ? Number(BigInt.asIntN(bits, v)) : Number(BigInt.asUintN(bits, v));
  if (bits === 32) return signed ? (v | 0) : (v >>> 0);
  if (bits === 1) return (v & 1);
  const m = Math.pow(2, bits);
  let r = Math.trunc(+v) % m;
  if (r < 0) r += m;
  if (signed && r >= m / 2) r -= m;
  return r;
}
function __sa_wide(v, signed) {
  // Widen any int-domain value to 64 bits, returned as BigInt.
  // BigInt inputs are 64-bit sources (modular); Number inputs are
  // 32-bit sources read with signed/unsigned 32-bit semantics.
  if (typeof v === "bigint") return signed ? BigInt.asIntN(64, v) : BigInt.asUintN(64, v);
  if (!Number.isFinite(+v)) return 0n;
  return signed ? BigInt((+v) | 0) : BigInt((+v) >>> 0);
}
function __sa_cvt_trunc_i8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_trunc_i16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_trunc_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_trunc_i32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_trunc_u8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_trunc_u16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_trunc_u32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_trunc_i64(v) { return __sa_wide(v, true); }
function __sa_cvt_trunc_u64(v) { return __sa_wide(v, false); }
function __sa_cvt_trunc_ptr(v) { return __sa_addr(v); }
function __sa_cvt_zext_i8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_zext_i16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_zext_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_zext_i32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_zext_u8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_zext_u16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_zext_u32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_zext_i64(v) { return (typeof v === "bigint") ? BigInt.asIntN(64, v) : BigInt((+v) >>> 0); }
function __sa_cvt_zext_u64(v) { return (typeof v === "bigint") ? BigInt.asUintN(64, v) : BigInt((+v) >>> 0); }
function __sa_cvt_zext_ptr(v) { return __sa_addr(v); }
function __sa_cvt_sext_i8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_sext_i16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_sext_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_sext_i32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_sext_u8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_sext_u16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_sext_u32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_sext_i64(v) { return (typeof v === "bigint") ? BigInt.asIntN(64, v) : BigInt((+v) | 0); }
function __sa_cvt_sext_u64(v) { return (typeof v === "bigint") ? BigInt.asUintN(64, v) : BigInt.asUintN(64, BigInt((+v) | 0)); }
function __sa_cvt_sext_ptr(v) { return __sa_addr(v); }
function __sa_cvt_sitofp_f64(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_cvt_sitofp_f32(v) { return Math.fround((typeof v === "bigint") ? Number(v) : (+v)); }
function __sa_cvt_uitofp_f64(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_cvt_uitofp_f32(v) { return Math.fround((typeof v === "bigint") ? Number(v) : (+v)); }
function __sa_cvt_fptosi_i64(v) {
  // Truncate toward zero like LLVM fptosi; out-of-range/NaN/Inf
  // maps to INT64_MIN (x86 cvttsd2si behavior) instead of throwing.
  const t = Math.trunc(+v);
  if (!Number.isFinite(t) || t >= 9223372036854775808 || t < -9223372036854775808) return -9223372036854775808n;
  return BigInt(t);
}
function __sa_cvt_fptosi_u64(v) { return BigInt.asUintN(64, __sa_cvt_fptosi_i64(v)); }
function __sa_cvt_fptosi_i32(v) { return Number(BigInt.asIntN(32, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u32(v) { return Number(BigInt.asUintN(32, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i16(v) { return Number(BigInt.asIntN(16, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u16(v) { return Number(BigInt.asUintN(16, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i8(v) { return Number(BigInt.asIntN(8, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u8(v) { return Number(BigInt.asUintN(8, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i1(v) { return Number(BigInt.asUintN(1, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_ptr(v) { return __sa_addr(__sa_cvt_fptosi_i64(v)); }
function __sa_cvt_fptrunc_f32(v) { return Math.fround(+v); }
function __sa_cvt_fpext_f64(v) { return (+v); }
const __sa_bc_dv = new DataView(new ArrayBuffer(8));
function __sa_cvt_bitcast_i8(v) { return (typeof v === "bigint") ? Number(BigInt.asIntN(8, v)) : ((v << 24) >> 24); }
function __sa_cvt_bitcast_u8(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(8, v)) : (v & 0xFF); }
function __sa_cvt_bitcast_i16(v) { return (typeof v === "bigint") ? Number(BigInt.asIntN(16, v)) : ((v << 16) >> 16); }
function __sa_cvt_bitcast_u16(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(16, v)) : (v & 0xFFFF); }
function __sa_cvt_bitcast_i1(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(1, v)) : (v & 1); }
function __sa_cvt_bitcast_i32(v) {
  // Non-integer Numbers are f32-domain values (f64 sources are
  // rejected by the verifier for 32-bit bitcasts); reinterpret them.
  if (typeof v === "bigint") return Number(BigInt.asIntN(32, v));
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat32(0, v, true); return __sa_bc_dv.getInt32(0, true); }
  return (v | 0);
}
function __sa_cvt_bitcast_u32(v) {
  if (typeof v === "bigint") return Number(BigInt.asUintN(32, v));
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat32(0, v, true); return __sa_bc_dv.getUint32(0, true); }
  return (v >>> 0);
}
function __sa_cvt_bitcast_i64(v) {
  // Non-integer Numbers are f64-domain values; reinterpret them.
  // Integer Numbers are immediates (f64-integral bitcasts are a
  // known edge; use sitofp-produced values only via fptosi).
  if (typeof v === "bigint") return BigInt.asIntN(64, v);
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat64(0, v, true); return __sa_bc_dv.getBigInt64(0, true); }
  return BigInt(v);
}
function __sa_cvt_bitcast_u64(v) {
  if (typeof v === "bigint") return BigInt.asUintN(64, v);
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat64(0, v, true); return BigInt.asUintN(64, __sa_bc_dv.getBigInt64(0, true)); }
  return BigInt(v);
}
function __sa_cvt_bitcast_ptr(v) {
  if (typeof v === "bigint") return Number(BigInt.asUintN(32, v));
  return (v | 0);
}
function __sa_cvt_bitcast_f32(v) {
  // BigInt/integer inputs are int-domain bits; fractional inputs are
  // already f32-domain values (f32-to-f32 is identity).
  if (typeof v === "bigint") { __sa_bc_dv.setUint32(0, Number(BigInt.asUintN(32, v)), true); return __sa_bc_dv.getFloat32(0, true); }
  if (!Number.isInteger(v)) return (+v);
  __sa_bc_dv.setInt32(0, v | 0, true); return __sa_bc_dv.getFloat32(0, true);
}
function __sa_cvt_bitcast_f64(v) {
  // Number inputs are always f64-domain here (equal-bits rule keeps
  // int-domain f64 bitcasts on the BigInt path).
  if (typeof v === "bigint") { __sa_bc_dv.setBigInt64(0, BigInt.asIntN(64, v), true); return __sa_bc_dv.getFloat64(0, true); }
  return (+v);
}
// ---- end runtime ----
// source: demos/js/302_http_server_saasm/main.sa
const __sa_ftable = [];
const C_HOST = 4096; // utf8 (9 bytes)
__sa_u8.set([49,50,55,46,48,46,48,46,49], 4096);
const C_PATH = 4112; // utf8 (7 bytes)
__sa_u8.set([47,115,116,114,101,97,109], 4112);
const C_HDR_KEY = 4120; // utf8 (12 bytes)
__sa_u8.set([99,111,110,116,101,110,116,45,116,121,112,101], 4120);
const C_HDR_VAL = 4136; // utf8 (10 bytes)
__sa_u8.set([116,101,120,116,47,112,108,97,105,110], 4136);
const C_CHUNK_1 = 4152; // utf8 (13 bytes)
__sa_u8.set([100,97,116,97,58,32,102,105,114,115,116,10,10], 4152);
const C_CHUNK_2 = 4168; // utf8 (14 bytes)
__sa_u8.set([100,97,116,97,58,32,115,101,99,111,110,100,10,10], 4168);
const C_RESULT_OK = 4184; // utf8 (3 bytes)
__sa_u8.set([111,107,10], 4184);
const C_RESULT_ERR = 4192; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4192);
export function main() {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = 0, r18 = 0, r19 = 0, r20 = 0, r21 = 0, r22 = 0, r23 = 0, r24 = 0, r25 = 0, r26 = 0, r27 = 0, r28 = 0, r29 = 0, r30 = 0, r31 = 0, r32 = 0, r33 = 0, r34 = 0, r35 = 0, r36 = 0, r37 = 0, r38 = 0, r39 = 0, r40 = 0, r41 = 0, r42 = 0, r43 = 0, r44 = 0, r45 = 0, r46 = 0, r47 = 0, r48 = 0, r49 = 0, r50 = 0, r51 = 0, r52 = C_HOST, r53 = C_PATH, r54 = C_HDR_KEY, r55 = C_HDR_VAL, r56 = C_CHUNK_1, r57 = C_CHUNK_2, r58 = C_RESULT_OK, r59 = C_RESULT_ERR;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = __sa_salloc(8n);
        r1 = sa_http_server_new(r0);
        r2 = __sa_load_i64(__sa_ptr_add(r0, 0n));
        r3 = sa_http_server_start(r2, C_HOST, 9, 18091);
        r4 = __sa_salloc(8n);
        r5 = __sa_salloc(8n);
        r6 = __sa_salloc(8n);
        r7 = __sa_salloc(8n);
        r8 = __sa_salloc(8n);
        r9 = __sa_salloc(8n);
        r10 = __sa_salloc(8n);
        r11 = __sa_salloc(8n);
        r12 = sa_http_server_accept(r2, r4);
        r13 = __sa_load_i64(__sa_ptr_add(r4, 0n));
        r14 = sa_http_server_req_get_path(r13, r6, r7);
        r15 = sa_http_server_req_get_header(r13, C_HDR_KEY, 12, r8, r9);
        r16 = sa_http_server_req_get_body(r13, r10, r11);
        r17 = sa_http_server_resp_stream_new(r13, 200, r5);
        r18 = __sa_load_i64(__sa_ptr_add(r5, 0n));
        r19 = sa_http_server_resp_stream_write(r18, C_CHUNK_1, 13);
        r20 = sa_http_server_resp_stream_flush(r18);
        r21 = sa_http_server_resp_stream_write(r18, C_CHUNK_2, 14);
        r22 = sa_http_server_resp_stream_flush(r18);
        r23 = sa_http_server_resp_stream_end(r18);
        r24 = __sa_load_i64(__sa_ptr_add(r6, 0n));
        r25 = __sa_load_i64(__sa_ptr_add(r7, 0n));
        r26 = __sa_load_i64(__sa_ptr_add(r8, 0n));
        r27 = __sa_load_i64(__sa_ptr_add(r9, 0n));
        r28 = __sa_load_i64(__sa_ptr_add(r11, 0n));
        r29 = __sa_load_u8(__sa_ptr_add(r24, 0n));
        r30 = __sa_load_u8(__sa_ptr_add(r26, 0n));
        r31 = __sa_load_u8(__sa_ptr_add(r24, 1n));
        r32 = __sa_load_u8(__sa_ptr_add(r26, 1n));
        r33 = __sa_eq(r25, 7n);
        r34 = __sa_eq(r27, 10n);
        r35 = __sa_eq(r29, 47n);
        r36 = __sa_eq(r30, 116n);
        r37 = __sa_eq(r31, 115n);
        r38 = __sa_eq(r32, 101n);
        r39 = __sa_eq(r14, 0n);
        r40 = __sa_eq(r15, 0n);
        r41 = __sa_eq(r16, 0n);
        r42 = __sa_eq(r17, 0n);
        r43 = __sa_eq(r19, 0n);
        r44 = __sa_eq(r20, 0n);
        r45 = __sa_eq(r21, 0n);
        r46 = __sa_eq(r22, 0n);
        r47 = __sa_eq(r23, 0n);
        r48 = __sa_eq(r12, 0n);
        r49 = __sa_eq(r1, 0n);
        r50 = __sa_eq(r3, 0n);
        r51 = __sa_band(r49, r50);
        r51 = __sa_band(r51, r48);
        r51 = __sa_band(r51, r39);
        r51 = __sa_band(r51, r40);
        r51 = __sa_band(r51, r42);
        r51 = __sa_band(r51, r43);
        r51 = __sa_band(r51, r44);
        r51 = __sa_band(r51, r45);
        r51 = __sa_band(r51, r46);
        r51 = __sa_band(r51, r47);
        r51 = __sa_band(r51, r33);
        r51 = __sa_band(r51, r34);
        r51 = __sa_band(r51, r35);
        r51 = __sa_band(r51, r36);
        r51 = __sa_band(r51, r37);
        r51 = __sa_band(r51, r38);
        sa_http_server_resp_stream_free(r18);
        sa_http_server_req_free(r13);
        sa_http_server_free(r2);
        /* no-op release: !server_status */
        /* no-op release: !start_status */
        /* no-op release: !accept_status */
        /* no-op release: !path_status */
        /* no-op release: !hdr_status */
        /* no-op release: !body_status */
        /* no-op release: !resp_status */
        /* no-op release: !write_1_status */
        /* no-op release: !flush_1_status */
        /* no-op release: !write_2_status */
        /* no-op release: !flush_2_status */
        /* no-op release: !end_status */
        /* no-op release: !ok_server */
        /* no-op release: !ok_start */
        /* no-op release: !ok_accept */
        /* no-op release: !ok_path */
        /* no-op release: !ok_hdr */
        /* no-op release: !ok_resp */
        /* no-op release: !ok_write_1 */
        /* no-op release: !ok_flush_1 */
        /* no-op release: !ok_write_2 */
        /* no-op release: !ok_flush_2 */
        /* no-op release: !ok_end */
        /* no-op release: !ok_path_len */
        /* no-op release: !ok_hdr_len */
        /* no-op release: !ok_path0 */
        /* no-op release: !ok_hdr0 */
        /* no-op release: !ok_path1 */
        /* no-op release: !ok_hdr1 */
        /* no-op release: !path0 */
        /* no-op release: !hdr0 */
        /* no-op release: !path1 */
        /* no-op release: !hdr1 */
        /* no-op release: !path_ptr */
        /* no-op release: !path_len */
        /* no-op release: !hdr_ptr */
        /* no-op release: !hdr_len */
        /* no-op release: !body_len */
        __pc = (__sa_truthy(r51) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_OK, 3);
        return {s: 0, v: (0)};
      }
      case 3: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_ERR, 6);
        return {s: 0, v: (1)};
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}
function sa_http_server_new(out_server) {
  globalThis.__sa_https = (globalThis.__sa_https || {});
  globalThis.__sa_http_sreq = (globalThis.__sa_http_sreq || {});
  globalThis.__sa_http_sresp = (globalThis.__sa_http_sresp || {});
  const h = __sa_alloc(8);
  globalThis.__sa_https[__sa_addr(h)] = {};
  __sa_store_ptr(out_server, h);
  return 0;
}
function sa_http_server_start(server, host, host_len, port) {
  const s = globalThis.__sa_https[__sa_addr(server)];
  if (!s) return 1;
  const a = __sa_addr(host), n = __sa_num(host_len);
  s.host = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  s.port = __sa_num(port);
  return 0;
}
function sa_http_server_accept(server, out_req) {
  if (!globalThis.__sa_https[__sa_addr(server)]) return 1;
  const h = __sa_alloc(8);
  globalThis.__sa_http_sreq[__sa_addr(h)] = {
    path: new globalThis.TextEncoder().encode("/stream"),
    hdr_val: new globalThis.TextEncoder().encode("text/plain"),
    body: new Uint8Array(0),
  };
  __sa_store_ptr(out_req, h);
  return 0;
}
function sa_http_server_req_get_path(req, out_path, out_len) {
  const r = globalThis.__sa_http_sreq[__sa_addr(req)];
  if (!r) return 1;
  const p = __sa_alloc(r.path.length);
  __sa_u8.set(r.path, p);
  __sa_store_ptr(out_path, p);
  __sa_store_i64(out_len, r.path.length);
  return 0;
}
function sa_http_server_req_get_header(req, key, key_len, out_val, out_len) {
  const r = globalThis.__sa_http_sreq[__sa_addr(req)];
  if (!r) return 1;
  const p = __sa_alloc(r.hdr_val.length);
  __sa_u8.set(r.hdr_val, p);
  __sa_store_ptr(out_val, p);
  __sa_store_i64(out_len, r.hdr_val.length);
  return 0;
}
function sa_http_server_req_get_body(req, out_body, out_len) {
  const r = globalThis.__sa_http_sreq[__sa_addr(req)];
  if (!r) return 1;
  __sa_store_ptr(out_body, 0);
  __sa_store_i64(out_len, 0);
  return 0;
}
function sa_http_server_resp_stream_new(req, status, out_resp) {
  if (!globalThis.__sa_http_sreq[__sa_addr(req)]) return 1;
  const h = __sa_alloc(8);
  globalThis.__sa_http_sresp[__sa_addr(h)] = { status: __sa_num(status), chunks: [] };
  __sa_store_ptr(out_resp, h);
  return 0;
}
function sa_http_server_resp_stream_write(resp, body, body_len) {
  const r = globalThis.__sa_http_sresp[__sa_addr(resp)];
  if (!r) return 1;
  const a = __sa_addr(body), n = __sa_num(body_len);
  r.chunks.push(__sa_u8.slice(a, a + n));
  return 0;
}
function sa_http_server_resp_stream_flush(resp) {
  return globalThis.__sa_http_sresp[__sa_addr(resp)] ? 0 : 1;
}
function sa_http_server_resp_stream_end(resp) {
  return globalThis.__sa_http_sresp[__sa_addr(resp)] ? 0 : 1;
}
function sa_http_server_resp_stream_free(resp) { delete globalThis.__sa_http_sresp[__sa_addr(resp)]; return 0; }
function sa_http_server_req_free(req) { delete globalThis.__sa_http_sreq[__sa_addr(req)]; return 0; }
function sa_http_server_free(server) { delete globalThis.__sa_https[__sa_addr(server)]; return 0; }

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc, __sa_free, __sa_salloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
