// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
const __sa_live = new Set(); // live heap bases (user pointers handed out by __sa_alloc)
const __sa_fl = Object.create(null); // free-list buckets: aligned size -> stack of user pointers
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((__sa_num(size) | 0), 8);
  const bucket = __sa_fl[size];
  if (bucket && bucket.length) { const ptr = bucket.pop(); __sa_u8.fill(0, ptr, ptr + size); __sa_live.add(ptr | 0); return ptr | 0; }
  const total = (size + 8); // 8-byte header holds the aligned user size
  const base = __sa_brk;
  __sa_brk += total;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, base, base + total);
  __sa_view.setUint32(base, size, true);
  const ptr = (base + 8);
  __sa_live.add(ptr | 0);
  return ptr | 0;
}
function __sa_free(ptr) {
  // Mirrors the interpreter: only exact live heap bases are recycled.
  // BigInt pointers are normalized to 32-bit addresses first so
  // 64-bit-typed bases stay freeable; interior pointers, consts and
  // unknown addresses remain no-ops (never present in __sa_live).
  const p = __sa_addr(ptr);
  if (!__sa_live.has(p)) return 0;
  __sa_live.delete(p);
  const size = __sa_view.getUint32((p - 8), true);
  (__sa_fl[size] || (__sa_fl[size] = [])).push(p);
  return 0;
}
const __sa_fstack = []; // call-stack of frames; each frame lists its stack slots
function __sa_salloc(size) {
  // Function-scoped allocation: freed when the owning frame returns
  // (mirrors stack-slot lifetime; the interpreter never frees these
  // mid-frame either). Returned to the free list on frame pop.
  const ptr = __sa_alloc(size);
  if (__sa_fstack.length) __sa_fstack[__sa_fstack.length - 1].push(ptr | 0);
  return ptr;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), __sa_narrow(v, 8, true)); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), __sa_narrow(v, 8, false)); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), __sa_narrow(v, 16, true), true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), __sa_narrow(v, 16, false), true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), __sa_narrow(v, 32, true), true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), __sa_narrow(v, 32, false), true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { const nb = (typeof b === "bigint") ? b : BigInt(b | 0); if (nb === 0n) __sa_trap("div by zero"); const na = (typeof a === "bigint") ? a : BigInt(a | 0); return __sa_BI(na / nb); } const nb32 = (b | 0); if (nb32 === 0) __sa_trap("div by zero"); return (Math.trunc((a | 0) / nb32) | 0); }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const x = (typeof a === "bigint") ? __sa_BU(a) : BigInt(a >>> 0); const y = (typeof b === "bigint") ? __sa_BU(b) : BigInt(b >>> 0); if (y === 0n) __sa_trap("div by zero"); return x / y; } const y32 = (b >>> 0); if (y32 === 0) __sa_trap("div by zero"); return Math.trunc((a >>> 0) / y32); }
function __sa_srem(a, b) { if (__sa_isBI(a, b)) { const nb = (typeof b === "bigint") ? b : BigInt(b | 0); if (nb === 0n) __sa_trap("rem by zero"); const na = (typeof a === "bigint") ? a : BigInt(a | 0); return __sa_BI(na % nb); } const nb32 = (b | 0); if (nb32 === 0) __sa_trap("rem by zero"); return (((a | 0) % nb32) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const x = (typeof a === "bigint") ? __sa_BU(a) : BigInt(a >>> 0); const y = (typeof b === "bigint") ? __sa_BU(b) : BigInt(b >>> 0); if (y === 0n) __sa_trap("rem by zero"); return x % y; } const y32 = (b >>> 0); if (y32 === 0) __sa_trap("rem by zero"); return ((a >>> 0) % y32); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { if (typeof a === "bigint") return __sa_BU(a) >> (BigInt(b) & 63n); return (a >>> (typeof b === "bigint" ? Number(BigInt(b) & 63n) & 31 : (b & 31))); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_narrow(v, bits, signed) {
  // Narrow any int-domain value to a target width, returned as Number.
  // BigInt inputs are 64-bit sources; Number inputs are 32-bit (or
  // smaller) sources. Matches interpreter wrap-around for
  // trunc/zext/sext/bitcast to widths <= 32.
  if (typeof v === "bigint") return signed ? Number(BigInt.asIntN(bits, v)) : Number(BigInt.asUintN(bits, v));
  if (bits === 32) return signed ? (v | 0) : (v >>> 0);
  if (bits === 1) return (v & 1);
  const m = Math.pow(2, bits);
  let r = Math.trunc(+v) % m;
  if (r < 0) r += m;
  if (signed && r >= m / 2) r -= m;
  return r;
}
function __sa_wide(v, signed) {
  // Widen any int-domain value to 64 bits, returned as BigInt.
  // BigInt inputs are 64-bit sources (modular); Number inputs are
  // 32-bit sources read with signed/unsigned 32-bit semantics.
  if (typeof v === "bigint") return signed ? BigInt.asIntN(64, v) : BigInt.asUintN(64, v);
  if (!Number.isFinite(+v)) return 0n;
  return signed ? BigInt((+v) | 0) : BigInt((+v) >>> 0);
}
function __sa_cvt_trunc_i8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_trunc_i16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_trunc_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_trunc_i32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_trunc_u8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_trunc_u16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_trunc_u32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_trunc_i64(v) { return __sa_wide(v, true); }
function __sa_cvt_trunc_u64(v) { return __sa_wide(v, false); }
function __sa_cvt_trunc_ptr(v) { return __sa_cvt_ptr64(v); }
function __sa_cvt_zext_i8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_zext_i16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_zext_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_zext_i32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_zext_u8(v) { return __sa_narrow(v, 8, false); }
function __sa_cvt_zext_u16(v) { return __sa_narrow(v, 16, false); }
function __sa_cvt_zext_u32(v) { return __sa_narrow(v, 32, false); }
function __sa_cvt_zext_i64(v) { return (typeof v === "bigint") ? BigInt.asIntN(64, v) : BigInt((+v) >>> 0); }
function __sa_cvt_zext_u64(v) { return (typeof v === "bigint") ? BigInt.asUintN(64, v) : BigInt((+v) >>> 0); }
function __sa_cvt_zext_ptr(v) { return __sa_cvt_ptr64(v); }
function __sa_cvt_sext_i8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_sext_i16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_sext_i1(v) { return __sa_narrow(v, 1, false); }
function __sa_cvt_sext_i32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_sext_u8(v) { return __sa_narrow(v, 8, true); }
function __sa_cvt_sext_u16(v) { return __sa_narrow(v, 16, true); }
function __sa_cvt_sext_u32(v) { return __sa_narrow(v, 32, true); }
function __sa_cvt_sext_i64(v) { return (typeof v === "bigint") ? BigInt.asIntN(64, v) : BigInt((+v) | 0); }
function __sa_cvt_sext_u64(v) { return (typeof v === "bigint") ? BigInt.asUintN(64, v) : BigInt.asUintN(64, BigInt((+v) | 0)); }
function __sa_cvt_sext_ptr(v) { return __sa_cvt_ptr64(v); }
function __sa_cvt_sitofp_f64(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_cvt_sitofp_f32(v) { return Math.fround((typeof v === "bigint") ? Number(v) : (+v)); }
function __sa_cvt_uitofp_f64(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_cvt_uitofp_f32(v) { return Math.fround((typeof v === "bigint") ? Number(v) : (+v)); }
function __sa_cvt_fptosi_i64(v) {
  // Truncate toward zero like LLVM fptosi; out-of-range/NaN/Inf
  // maps to INT64_MIN (x86 cvttsd2si behavior) instead of throwing.
  const t = Math.trunc(+v);
  if (!Number.isFinite(t) || t >= 9223372036854775808 || t < -9223372036854775808) return -9223372036854775808n;
  return BigInt(t);
}
function __sa_cvt_fptosi_u64(v) { return BigInt.asUintN(64, __sa_cvt_fptosi_i64(v)); }
function __sa_cvt_fptosi_i32(v) { return Number(BigInt.asIntN(32, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u32(v) { return Number(BigInt.asUintN(32, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i16(v) { return Number(BigInt.asIntN(16, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u16(v) { return Number(BigInt.asUintN(16, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i8(v) { return Number(BigInt.asIntN(8, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_u8(v) { return Number(BigInt.asUintN(8, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_i1(v) { return Number(BigInt.asUintN(1, __sa_cvt_fptosi_i64(v))); }
function __sa_cvt_fptosi_ptr(v) { return __sa_addr(__sa_cvt_fptosi_i64(v)); }
function __sa_cvt_fptrunc_f32(v) { return Math.fround(+v); }
function __sa_cvt_fpext_f64(v) { return (+v); }
const __sa_bc_dv = new DataView(new ArrayBuffer(8));
function __sa_cvt_bitcast_i8(v) { return (typeof v === "bigint") ? Number(BigInt.asIntN(8, v)) : ((v << 24) >> 24); }
function __sa_cvt_bitcast_u8(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(8, v)) : (v & 0xFF); }
function __sa_cvt_bitcast_i16(v) { return (typeof v === "bigint") ? Number(BigInt.asIntN(16, v)) : ((v << 16) >> 16); }
function __sa_cvt_bitcast_u16(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(16, v)) : (v & 0xFFFF); }
function __sa_cvt_bitcast_i1(v) { return (typeof v === "bigint") ? Number(BigInt.asUintN(1, v)) : (v & 1); }
function __sa_cvt_bitcast_i32(v) {
  // Non-integer Numbers are f32-domain values (f64 sources are
  // rejected by the verifier for 32-bit bitcasts); reinterpret them.
  if (typeof v === "bigint") return Number(BigInt.asIntN(32, v));
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat32(0, v, true); return __sa_bc_dv.getInt32(0, true); }
  return (v | 0);
}
function __sa_cvt_bitcast_u32(v) {
  if (typeof v === "bigint") return Number(BigInt.asUintN(32, v));
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat32(0, v, true); return __sa_bc_dv.getUint32(0, true); }
  return (v >>> 0);
}
function __sa_cvt_bitcast_i64(v) {
  // Non-integer Numbers are f64-domain values; reinterpret them.
  // Integer Numbers are immediates (f64-integral bitcasts are a
  // known edge; use sitofp-produced values only via fptosi).
  if (typeof v === "bigint") return BigInt.asIntN(64, v);
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat64(0, v, true); return __sa_bc_dv.getBigInt64(0, true); }
  return BigInt(v);
}
function __sa_cvt_bitcast_u64(v) {
  if (typeof v === "bigint") return BigInt.asUintN(64, v);
  if (!Number.isInteger(v)) { __sa_bc_dv.setFloat64(0, v, true); return BigInt.asUintN(64, __sa_bc_dv.getBigInt64(0, true)); }
  return BigInt(v);
}
function __sa_cvt_bitcast_ptr(v) {
  // Pointers carry full 64-bit patterns in every backend (only
  // real heap bases are 32-bit); narrowing here would break
  // bitcast roundtrips of high-bit patterns.
  if (typeof v === "bigint") return BigInt.asUintN(64, v);
  return v;
}
function __sa_cvt_ptr64(v) {
  // 64-bit-preserving pointer conversion (trunc/zext/sext to ptr):
  // same as bitcast_ptr, factored for the int-conversion family.
  if (typeof v === "bigint") return BigInt.asUintN(64, v);
  return v;
}
function __sa_cvt_bitcast_f32(v) {
  // BigInt/integer inputs are int-domain bits; fractional inputs are
  // already f32-domain values (f32-to-f32 is identity).
  if (typeof v === "bigint") { __sa_bc_dv.setUint32(0, Number(BigInt.asUintN(32, v)), true); return __sa_bc_dv.getFloat32(0, true); }
  if (!Number.isInteger(v)) return (+v);
  __sa_bc_dv.setInt32(0, v | 0, true); return __sa_bc_dv.getFloat32(0, true);
}
function __sa_cvt_bitcast_f64(v) {
  // Number inputs are always f64-domain here (equal-bits rule keeps
  // int-domain f64 bitcasts on the BigInt path).
  if (typeof v === "bigint") { __sa_bc_dv.setBigInt64(0, BigInt.asIntN(64, v), true); return __sa_bc_dv.getFloat64(0, true); }
  return (+v);
}
function __sa_srcmask(v, w, signed) {
  // Restrict a value to a known source width (statically tracked by
  // the emitter for load-defined slots) before zext/sext, so
  // sub-32-bit sources (e.g. i8 0xFF) extend from the right bits
  // instead of the 32-bit value-inference default.
  if (typeof v === "bigint") return signed ? BigInt.asIntN(w, v) : BigInt.asUintN(w, v);
  if (w >= 64) return v;
  if (w === 32) return signed ? (v | 0) : (v >>> 0);
  if (w === 1) return (v & 1);
  const s = 32 - w;
  return signed ? ((v << s) >> s) : (((v << s) >>> s));
}
function __sa_cvt_bitcast_f64i(v) {
  // int-domain source with a 64-bit target: reinterpret the bits.
  // Used when the emitter statically knows the source is integral
  // (plain bitcast_f64 treats Numbers as f64-domain values).
  const b = (typeof v === "bigint") ? BigInt.asIntN(64, v) : BigInt(Math.trunc(+v));
  __sa_bc_dv.setBigInt64(0, b, true); return __sa_bc_dv.getFloat64(0, true);
}
function __sa_cvt_bitcast_i32f(v) {
  // float-domain f32 source reinterpreted as i32 (emitter-known).
  __sa_bc_dv.setFloat32(0, +v, true); return __sa_bc_dv.getInt32(0, true);
}
function __sa_cvt_bitcast_u32f(v) {
  __sa_bc_dv.setFloat32(0, +v, true); return __sa_bc_dv.getUint32(0, true);
}
function __sa_cvt_bitcast_i64b(v) {
  // float-domain f64 source reinterpreted as i64 (emitter-known).
  __sa_bc_dv.setFloat64(0, +v, true); return __sa_bc_dv.getBigInt64(0, true);
}
function __sa_cvt_bitcast_u64b(v) {
  __sa_bc_dv.setFloat64(0, +v, true); return BigInt.asUintN(64, __sa_bc_dv.getBigInt64(0, true));
}
// ---- end runtime ----
// source: demos/rosetta/88_text_index/main.sa
const __sa_ftable = [];
const C_RESULT_OK = 4096; // utf8 (2 bytes)
__sa_u8.set([51,10], 4096);
const C_RESULT_ERR = 4104; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4104);
export function count_words(a, b, c) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = C_RESULT_OK, r6 = C_RESULT_ERR;
  r0 = a;
  r1 = b;
  r2 = c;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_add(r0, r1);
        r4 = __sa_add(r3, r2);
        /* no-op release: !a */
        /* no-op release: !b */
        /* no-op release: !c */
        /* no-op release: !ab */
        return (r4);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function main() {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = C_RESULT_OK, r3 = C_RESULT_ERR;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = count_words(1, 1, 1);
        r1 = __sa_eq(r0, 3n);
        /* no-op release: !total */
        __pc = (__sa_truthy(r1) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_OK, 2);
        return (0);
      }
      case 3: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_ERR, 6);
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc, __sa_free, __sa_salloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
