// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((size | 0), 8);
  const ptr = __sa_brk;
  __sa_brk += size;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, ptr, ptr + size);
  return ptr | 0;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), v | 0); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), v | 0); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), v | 0, true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), v | 0, true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), v | 0, true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), v >>> 0, true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a) / d); } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a) % d); } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_cvt(v) { return v; }
// ---- end runtime ----
// source: /content/sa_all/sci/demos/rosetta/190_base64_encode_simd/main.sa
const __sa_ftable = [];
const C_RESULT_OK = 4096; // utf8 (5 bytes)
__sa_u8.set([84,87,70,117,10], 4096);
const C_RESULT_ERR = 4104; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4104);
const C_B64 = 4112; // utf8 (64 bytes)
__sa_u8.set([65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,43,47], 4112);
export function encode_block(out, input) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = C_B64, r17 = 0, r18 = 0, r19 = 0, r20 = 0, r21 = 0, r22 = 0, r23 = 0, r24 = 0, r25 = 0, r26 = 0, r27 = 0, r28 = 0, r29 = 0, r30 = 0, r31 = 0, r32 = C_RESULT_OK, r33 = C_RESULT_ERR;
  r0 = out;
  r1 = input;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r2 = __sa_load_u8(__sa_ptr_add(r1, 0));
        r3 = __sa_load_u8(__sa_ptr_add(r1, 1));
        r4 = __sa_load_u8(__sa_ptr_add(r1, 2));
        r5 = __sa_sdiv(r2, 4);
        r6 = __sa_srem(r2, 4);
        r7 = __sa_mul(r6, 16);
        r8 = __sa_sdiv(r3, 16);
        r9 = __sa_add(r7, r8);
        r10 = __sa_srem(r3, 16);
        r11 = __sa_mul(r10, 4);
        r12 = __sa_sdiv(r4, 64);
        r13 = __sa_add(r11, r12);
        r14 = __sa_srem(r4, 64);
        r15 = (r16);
        r17 = __sa_ptr_add(r15, r5);
        r18 = __sa_ptr_add(r15, r9);
        r19 = __sa_ptr_add(r15, r13);
        r20 = __sa_ptr_add(r15, r14);
        r21 = __sa_load_u8(__sa_ptr_add(r17, 0));
        r22 = __sa_load_u8(__sa_ptr_add(r18, 0));
        r23 = __sa_load_u8(__sa_ptr_add(r19, 0));
        r24 = __sa_load_u8(__sa_ptr_add(r20, 0));
        __sa_store_u8(__sa_ptr_add(r0, 0), r21);
        __sa_store_u8(__sa_ptr_add(r0, 1), r22);
        __sa_store_u8(__sa_ptr_add(r0, 2), r23);
        __sa_store_u8(__sa_ptr_add(r0, 3), r24);
        r25 = __sa_eq(r21, 84);
        r26 = __sa_eq(r22, 87);
        r27 = __sa_eq(r23, 70);
        r28 = __sa_eq(r24, 117);
        r29 = __sa_band(r25, r26);
        r30 = __sa_band(r27, r28);
        r31 = __sa_band(r29, r30);
        /* no-op release: !b0 */
        /* no-op release: !b1 */
        /* no-op release: !b2 */
        /* no-op release: !q0 */
        /* no-op release: !q1_hi_mod */
        /* no-op release: !q1_mask */
        /* no-op release: !q1_lo */
        /* no-op release: !q1 */
        /* no-op release: !q2_hi_mod */
        /* no-op release: !q2_mask */
        /* no-op release: !q2_lo */
        /* no-op release: !q2 */
        /* no-op release: !q3 */
        /* no-op release: !alpha */
        /* no-op release: !c0 */
        /* no-op release: !c1 */
        /* no-op release: !c2 */
        /* no-op release: !c3 */
        /* no-op release: !ok0 */
        /* no-op release: !ok1 */
        /* no-op release: !ok2 */
        /* no-op release: !ok3 */
        /* no-op release: !ok */
        /* no-op release: !ok1a */
        /* no-op release: !input */
        /* no-op release: !out */
        __pc = (__sa_truthy(r31) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok2a */
        return (4);
      }
      case 3: {
        /* no-op release: !ok2a */
        return (0);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function main() {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = C_RESULT_OK, r17 = C_RESULT_ERR, r18 = C_B64;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = __sa_alloc(4);
        r1 = __sa_alloc(8);
        __sa_store_u8(__sa_ptr_add(r0, 0), 77);
        __sa_store_u8(__sa_ptr_add(r0, 1), 97);
        __sa_store_u8(__sa_ptr_add(r0, 2), 110);
        __sa_store_u8(__sa_ptr_add(r0, 3), 0);
        r2 = encode_block(r1, r0);
        r3 = __sa_load_u8(__sa_ptr_add(r1, 0));
        r4 = __sa_load_u8(__sa_ptr_add(r1, 1));
        r5 = __sa_load_u8(__sa_ptr_add(r1, 2));
        r6 = __sa_load_u8(__sa_ptr_add(r1, 3));
        r7 = __sa_eq(r3, 84);
        r8 = __sa_eq(r4, 87);
        r9 = __sa_eq(r5, 70);
        r10 = __sa_eq(r6, 117);
        r11 = __sa_eq(r2, 4);
        r12 = __sa_band(r7, r8);
        r13 = __sa_band(r9, r10);
        r14 = __sa_band(r12, r13);
        r15 = __sa_band(r14, r11);
        /* no-op release: !c0 */
        /* no-op release: !c1 */
        /* no-op release: !c2 */
        /* no-op release: !c3 */
        /* no-op release: !len */
        /* no-op release: !ok0 */
        /* no-op release: !ok1 */
        /* no-op release: !ok2 */
        /* no-op release: !ok3 */
        /* no-op release: !ok4 */
        /* no-op release: !pair0 */
        /* no-op release: !pair1 */
        /* no-op release: !pair2 */
        /* no-op release: !input */
        /* no-op release: !out */
        __pc = (__sa_truthy(r15) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_OK, 5);
        return (0);
      }
      case 3: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_ERR, 6);
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
