// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((size | 0), 8);
  const ptr = __sa_brk;
  __sa_brk += size;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, ptr, ptr + size);
  return ptr | 0;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), v | 0); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), v | 0); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), v | 0, true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), v | 0, true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), v | 0, true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), v >>> 0, true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a) / d); } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a) % d); } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_cvt(v) { return v; }
// ---- end runtime ----
// source: /content/sa_all/sci/demos/support/mpsc_probe.sa
const __sa_ftable = [];
const C_RESULT_OK = 4096; // utf8 (8 bytes)
__sa_u8.set([109,112,115,99,32,111,107,10], 4096);
const C_RESULT_ERR = 4104; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4104);
export function sa_mem_copy(dst, src, count) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = 0, r18 = 0, r19 = 0;
  r0 = dst;
  r1 = src;
  r2 = count;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_ne(r2, 0);
        __pc = (__sa_truthy(r3) ? 2 : 7); break;
      }
      case 2: {
        r4 = __sa_eq(r0, 0);
        __pc = (__sa_truthy(r4) ? 3 : 4); break;
      }
      case 3: {
        __sa_panic(1701);
        __pc = 4; break;
      }
      case 4: {
        r5 = __sa_eq(r1, 0);
        __pc = (__sa_truthy(r5) ? 5 : 6); break;
      }
      case 5: {
        __sa_panic(1702);
        __pc = 6; break;
      }
      case 6: {
        /* no-op release: !src_null */
        /* no-op release: !dst_null */
        __pc = 7; break;
      }
      case 7: {
        r6 = __sa_alloc(8);
        r7 = __sa_alloc(8);
        r8 = __sa_alloc(8);
        r9 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r6, 0), 0);
        r10 = __sa_load_i64(__sa_ptr_add(r6, 0));
        __sa_store_i64(__sa_ptr_add(r7, 0), 1);
        r11 = __sa_load_i64(__sa_ptr_add(r7, 0));
        __sa_store_i64(__sa_ptr_add(r8, 0), 0);
        __sa_store_i64(__sa_ptr_add(r9, 0), r2);
        __pc = 8; break;
      }
      case 8: {
        r12 = __sa_load_i64(__sa_ptr_add(r8, 0));
        r13 = __sa_load_i64(__sa_ptr_add(r9, 0));
        r14 = __sa_eq(r13, r10);
        __pc = (__sa_truthy(r14) ? 10 : 9); break;
      }
      case 9: {
        r15 = __sa_ptr_add(r1, r12);
        r16 = __sa_ptr_add(r0, r12);
        r17 = __sa_load_u8(__sa_ptr_add(r15, 0));
        __sa_store_u8(__sa_ptr_add(r16, 0), r17);
        r18 = __sa_add(r12, r11);
        r19 = __sa_sub(r13, r11);
        /* no-op release: !src_ip */
        /* no-op release: !dst_ip */
        /* no-op release: !byte */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !done */
        __sa_store_i64(__sa_ptr_add(r8, 0), r18);
        __sa_store_i64(__sa_ptr_add(r9, 0), r19);
        /* no-op release: !next_offset */
        /* no-op release: !next_remaining */
        __pc = 8; break;
      }
      case 10: {
        /* no-op release: !done */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !one */
        /* no-op release: !zero */
        /* no-op release: !nonzero */
        /* no-op release: !count */
        /* no-op release: !src */
        /* no-op release: !dst */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function sa_mem_set(dst, val, count) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0;
  r0 = dst;
  r1 = val;
  r2 = count;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_ne(r2, 0);
        __pc = (__sa_truthy(r3) ? 2 : 5); break;
      }
      case 2: {
        r4 = __sa_eq(r0, 0);
        __pc = (__sa_truthy(r4) ? 3 : 4); break;
      }
      case 3: {
        __sa_panic(1703);
        __pc = 4; break;
      }
      case 4: {
        /* no-op release: !dst_null */
        __pc = 5; break;
      }
      case 5: {
        r5 = __sa_alloc(8);
        r6 = __sa_alloc(8);
        r7 = __sa_alloc(8);
        r8 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r5, 0), 0);
        r9 = __sa_load_i64(__sa_ptr_add(r5, 0));
        __sa_store_i64(__sa_ptr_add(r6, 0), 1);
        r10 = __sa_load_i64(__sa_ptr_add(r6, 0));
        __sa_store_i64(__sa_ptr_add(r7, 0), 0);
        __sa_store_i64(__sa_ptr_add(r8, 0), r2);
        __pc = 6; break;
      }
      case 6: {
        r11 = __sa_load_i64(__sa_ptr_add(r7, 0));
        r12 = __sa_load_i64(__sa_ptr_add(r8, 0));
        r13 = __sa_eq(r12, r9);
        __pc = (__sa_truthy(r13) ? 8 : 7); break;
      }
      case 7: {
        r14 = __sa_ptr_add(r0, r11);
        __sa_store_u8(__sa_ptr_add(r14, 0), r1);
        r15 = __sa_add(r11, r10);
        r16 = __sa_sub(r12, r10);
        /* no-op release: !dst_ip */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !done */
        __sa_store_i64(__sa_ptr_add(r7, 0), r15);
        __sa_store_i64(__sa_ptr_add(r8, 0), r16);
        /* no-op release: !next_offset */
        /* no-op release: !next_remaining */
        __pc = 6; break;
      }
      case 8: {
        /* no-op release: !done */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !one */
        /* no-op release: !zero */
        /* no-op release: !nonzero */
        /* no-op release: !count */
        /* no-op release: !val */
        /* no-op release: !dst */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function __mpsc_try_send(chan, value_slot) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0;
  r0 = chan;
  r1 = value_slot;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r2 = __sa_load_i64(__sa_ptr_add(r0, 0));
        r3 = __sa_load_i64(__sa_ptr_add(r0, 8));
        r4 = __sa_load_i64(__sa_ptr_add(r0, 16));
        r5 = __sa_uge(r4, r3);
        __pc = (__sa_truthy(r5) ? 3 : 2); break;
      }
      case 2: {
        r6 = __sa_add(r2, 0);
        __pc = 4; break;
      }
      case 3: {
        r6 = __sa_sub(r4, r3);
        __pc = 4; break;
      }
      case 4: {
        r7 = __sa_uge(r6, r2);
        __pc = (__sa_truthy(r7) ? 5 : 6); break;
      }
      case 5: {
        /* no-op release: !full */
        /* no-op release: !used */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (0);
      }
      case 6: {
        r8 = __sa_add(r4, 1);
        { const __addr = __sa_ptr_add(r0, 16); const __old = __sa_load_i64(__addr); const __exp = (r4); const __ok = ((__old == __exp) ? 1 : 0); if (__ok) __sa_store_i64(__addr, (r8)); r9 = __old; r10 = __ok; }
        __pc = (__sa_truthy(r10) ? 8 : 7); break;
      }
      case 7: {
        /* no-op release: !old_tail */
        /* no-op release: !ok */
        /* no-op release: !next_tail */
        /* no-op release: !full */
        /* no-op release: !used */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (0);
      }
      case 8: {
        r11 = __sa_urem(r4, r2);
        r12 = __sa_ptr_add(r0, 32);
        r13 = __sa_mul(r11, 16);
        r14 = __sa_ptr_add(r12, r13);
        r15 = __sa_load_i64(__sa_ptr_add(r1, 0));
        __sa_store_i64(__sa_ptr_add(r14, 0), r15);
        __sa_store_i64(__sa_ptr_add(r14, 8), 1);
        /* no-op release: !message */
        /* no-op release: !slot */
        /* no-op release: !slot_index */
        /* no-op release: !slot_off */
        /* no-op release: !slot_base */
        /* no-op release: !old_tail */
        /* no-op release: !ok */
        /* no-op release: !next_tail */
        /* no-op release: !full */
        /* no-op release: !used */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function __mpsc_try_recv(chan, out_value_slot) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0;
  r0 = chan;
  r1 = out_value_slot;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r2 = __sa_load_i64(__sa_ptr_add(r0, 0));
        r3 = __sa_load_i64(__sa_ptr_add(r0, 8));
        r4 = __sa_load_i64(__sa_ptr_add(r0, 16));
        r5 = __sa_uge(r4, r3);
        __pc = (__sa_truthy(r5) ? 3 : 2); break;
      }
      case 2: {
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (0);
      }
      case 3: {
        r6 = __sa_eq(r3, r4);
        __pc = (__sa_truthy(r6) ? 4 : 5); break;
      }
      case 4: {
        /* no-op release: !empty */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (0);
      }
      case 5: {
        r7 = __sa_urem(r3, r2);
        r8 = __sa_ptr_add(r0, 32);
        r9 = __sa_mul(r7, 16);
        r10 = __sa_ptr_add(r8, r9);
        r11 = __sa_load_i64(__sa_ptr_add(r10, 8));
        r12 = __sa_eq(r11, 1);
        __pc = (__sa_truthy(r12) ? 7 : 6); break;
      }
      case 6: {
        /* no-op release: !is_ready */
        /* no-op release: !ready */
        /* no-op release: !slot */
        /* no-op release: !slot_index */
        /* no-op release: !slot_off */
        /* no-op release: !slot_base */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (0);
      }
      case 7: {
        r13 = __sa_load_i64(__sa_ptr_add(r10, 0));
        __sa_store_i64(__sa_ptr_add(r10, 8), 0);
        r14 = __sa_add(r3, 1);
        __sa_store_i64(__sa_ptr_add(r0, 8), r14);
        __sa_store_i64(__sa_ptr_add(r1, 0), r13);
        /* no-op release: !message */
        /* no-op release: !next_head */
        /* no-op release: !is_ready */
        /* no-op release: !ready */
        /* no-op release: !slot */
        /* no-op release: !slot_index */
        /* no-op release: !slot_off */
        /* no-op release: !slot_base */
        /* no-op release: !tail_ok */
        /* no-op release: !tail */
        /* no-op release: !head */
        /* no-op release: !cap */
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function __mpsc_try_recv_timeout_ns(chan, out_value_slot, timeout_ns) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0;
  r0 = chan;
  r1 = out_value_slot;
  r2 = timeout_ns;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = sa_time_instant_ns();
        r4 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r4, 0), 1);
        __pc = 2; break;
      }
      case 2: {
        r5 = __mpsc_try_recv(r0, r1);
        __pc = (__sa_truthy(r5) ? 3 : 4); break;
      }
      case 3: {
        /* no-op release: !start */
        /* no-op release: !timeout_ns */
        return (1);
      }
      case 4: {
        r6 = sa_time_instant_ns();
        r7 = __sa_sub(r6, r3);
        r8 = __sa_uge(r7, r2);
        /* no-op release: !now */
        /* no-op release: !elapsed */
        __pc = (__sa_truthy(r8) ? 8 : 5); break;
      }
      case 5: {
        r9 = __sa_load_i64(__sa_ptr_add(r4, 0));
        sa_time_sleep_ns(r9);
        r10 = __sa_uge(r9, 1024);
        __pc = (__sa_truthy(r10) ? 7 : 6); break;
      }
      case 6: {
        r11 = __sa_shl(r9, 1);
        __sa_store_i64(__sa_ptr_add(r4, 0), r11);
        /* no-op release: !next */
        /* no-op release: !at_limit */
        /* no-op release: !backoff_ns */
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        __pc = 2; break;
      }
      case 7: {
        /* no-op release: !at_limit */
        /* no-op release: !backoff_ns */
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        __pc = 2; break;
      }
      case 8: {
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        /* no-op release: !start */
        /* no-op release: !timeout_ns */
        return (0);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function __mpsc_try_send_timeout_ns(chan, value_slot, timeout_ns) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = C_RESULT_OK, r13 = C_RESULT_ERR;
  r0 = chan;
  r1 = value_slot;
  r2 = timeout_ns;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = sa_time_instant_ns();
        r4 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r4, 0), 1);
        __pc = 2; break;
      }
      case 2: {
        r5 = __mpsc_try_send(r0, r1);
        __pc = (__sa_truthy(r5) ? 3 : 4); break;
      }
      case 3: {
        /* no-op release: !chan */
        /* no-op release: !value_slot */
        /* no-op release: !start */
        /* no-op release: !timeout_ns */
        return (1);
      }
      case 4: {
        r6 = sa_time_instant_ns();
        r7 = __sa_sub(r6, r3);
        r8 = __sa_uge(r7, r2);
        /* no-op release: !now */
        /* no-op release: !elapsed */
        __pc = (__sa_truthy(r8) ? 8 : 5); break;
      }
      case 5: {
        r9 = __sa_load_i64(__sa_ptr_add(r4, 0));
        sa_time_sleep_ns(r9);
        r10 = __sa_uge(r9, 1024);
        __pc = (__sa_truthy(r10) ? 7 : 6); break;
      }
      case 6: {
        r11 = __sa_shl(r9, 1);
        __sa_store_i64(__sa_ptr_add(r4, 0), r11);
        /* no-op release: !next */
        /* no-op release: !at_limit */
        /* no-op release: !backoff_ns */
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        __pc = 2; break;
      }
      case 7: {
        /* no-op release: !at_limit */
        /* no-op release: !backoff_ns */
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        __pc = 2; break;
      }
      case 8: {
        /* no-op release: !chan */
        /* no-op release: !value_slot */
        /* no-op release: !timed_out */
        /* no-op release: !ok */
        /* no-op release: !start */
        /* no-op release: !timeout_ns */
        return (0);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function producer_a(chan) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = C_RESULT_OK, r8 = C_RESULT_ERR;
  r0 = chan;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r1 = (10);
        r2 = (20);
        r3 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r3, 0), r1);
        __pc = 2; break;
      }
      case 2: {
        r4 = __mpsc_try_send(r0, r3);
        __pc = (__sa_truthy(r4) ? 4 : 3); break;
      }
      case 3: {
        /* no-op release: !__mpsc_send_ok_v10 */
        sa_time_sleep_ns(1);
        __pc = 2; break;
      }
      case 4: {
        /* no-op release: !v10 */
        /* no-op release: !__mpsc_send_ok_v10 */
        r5 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r5, 0), r2);
        __pc = 5; break;
      }
      case 5: {
        r6 = __mpsc_try_send(r0, r5);
        __pc = (__sa_truthy(r6) ? 7 : 6); break;
      }
      case 6: {
        /* no-op release: !__mpsc_send_ok_v20 */
        sa_time_sleep_ns(1);
        __pc = 5; break;
      }
      case 7: {
        /* no-op release: !v20 */
        /* no-op release: !__mpsc_send_ok_v20 */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function producer_b(chan) {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = C_RESULT_OK, r8 = C_RESULT_ERR;
  r0 = chan;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r1 = (30);
        r2 = (40);
        r3 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r3, 0), r1);
        __pc = 2; break;
      }
      case 2: {
        r4 = __mpsc_try_send(r0, r3);
        __pc = (__sa_truthy(r4) ? 4 : 3); break;
      }
      case 3: {
        /* no-op release: !__mpsc_send_ok_v30 */
        sa_time_sleep_ns(1);
        __pc = 2; break;
      }
      case 4: {
        /* no-op release: !v30 */
        /* no-op release: !__mpsc_send_ok_v30 */
        r5 = __sa_alloc(8);
        __sa_store_i64(__sa_ptr_add(r5, 0), r2);
        __pc = 5; break;
      }
      case 5: {
        r6 = __mpsc_try_send(r0, r5);
        __pc = (__sa_truthy(r6) ? 7 : 6); break;
      }
      case 6: {
        /* no-op release: !__mpsc_send_ok_v40 */
        sa_time_sleep_ns(1);
        __pc = 5; break;
      }
      case 7: {
        /* no-op release: !v40 */
        /* no-op release: !__mpsc_send_ok_v40 */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function main() {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = 0, r18 = 0, r19 = 0, r20 = 0, r21 = 0, r22 = 0, r23 = 0, r24 = 0, r25 = 0, r26 = 0, r27 = 0, r28 = 0, r29 = 0, r30 = 0, r31 = 0, r32 = C_RESULT_OK, r33 = C_RESULT_ERR;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = __sa_eq(4, 0);
        r1 = __sa_add(4, r0);
        r2 = __sa_eq(16, 0);
        __pc = (__sa_truthy(r2) ? 5 : 2); break;
      }
      case 2: {
        r3 = __sa_mul(r1, 16);
        r4 = __sa_udiv(r3, 16);
        r5 = __sa_eq(r4, r1);
        __pc = (__sa_truthy(r5) ? 3 : 4); break;
      }
      case 3: {
        r6 = __sa_add(r3, 0);
        r7 = __sa_add(0, 1);
        /* no-op release: !__num_mul_ok___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_roundtrip___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_product___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_rhs_zero___mpsc_data_ok_chan */
        __pc = 6; break;
      }
      case 4: {
        r6 = __sa_add(0, 0);
        r7 = __sa_add(0, 0);
        /* no-op release: !__num_mul_ok___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_roundtrip___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_product___mpsc_data_ok_chan */
        /* no-op release: !__num_mul_rhs_zero___mpsc_data_ok_chan */
        __pc = 6; break;
      }
      case 5: {
        r6 = __sa_add(0, 0);
        r7 = __sa_add(0, 1);
        /* no-op release: !__num_mul_rhs_zero___mpsc_data_ok_chan */
        __pc = 6; break;
      }
      case 6: {
        __pc = (__sa_truthy(r7) ? 8 : 7); break;
      }
      case 7: {
        __sa_panic(1401);
        __pc = 8; break;
      }
      case 8: {
        r8 = __sa_add(32, r6);
        r9 = __sa_ult(r8, 32);
        __pc = (__sa_truthy(r9) ? 10 : 9); break;
      }
      case 9: {
        r10 = __sa_add(r8, 0);
        r11 = __sa_add(0, 1);
        /* no-op release: !__num_add_overflow___mpsc_total_ok_chan */
        /* no-op release: !__num_add_sum___mpsc_total_ok_chan */
        __pc = 11; break;
      }
      case 10: {
        r10 = __sa_add(0, 0);
        r11 = __sa_add(0, 0);
        /* no-op release: !__num_add_overflow___mpsc_total_ok_chan */
        /* no-op release: !__num_add_sum___mpsc_total_ok_chan */
        __pc = 11; break;
      }
      case 11: {
        __pc = (__sa_truthy(r11) ? 13 : 12); break;
      }
      case 12: {
        __sa_panic(1402);
        __pc = 13; break;
      }
      case 13: {
        r12 = __sa_alloc(r10);
        sa_mem_set(r12, 0, r10);
        __sa_store_i64(__sa_ptr_add(r12, 0), r1);
        __sa_store_i64(__sa_ptr_add(r12, 8), 0);
        __sa_store_i64(__sa_ptr_add(r12, 16), 0);
        /* no-op release: !__mpsc_total_ok_chan */
        /* no-op release: !__mpsc_total_bytes_chan */
        /* no-op release: !__mpsc_data_ok_chan */
        /* no-op release: !__mpsc_data_bytes_chan */
        /* no-op release: !__mpsc_cap_chan */
        /* no-op release: !__mpsc_cap_is_zero_chan */
        producer_a(r12);
        producer_b(r12);
        r13 = __sa_alloc(8);
        __pc = 14; break;
      }
      case 14: {
        r14 = __mpsc_try_recv(r12, r13);
        __pc = (__sa_truthy(r14) ? 16 : 15); break;
      }
      case 15: {
        /* no-op release: !__mpsc_recv_ok_first */
        sa_time_sleep_ns(1);
        __pc = 14; break;
      }
      case 16: {
        r15 = __sa_load_i64(__sa_ptr_add(r13, 0));
        /* no-op release: !__mpsc_recv_ok_first */
        r16 = __sa_alloc(8);
        __pc = 17; break;
      }
      case 17: {
        r17 = __mpsc_try_recv(r12, r16);
        __pc = (__sa_truthy(r17) ? 19 : 18); break;
      }
      case 18: {
        /* no-op release: !__mpsc_recv_ok_second */
        sa_time_sleep_ns(1);
        __pc = 17; break;
      }
      case 19: {
        r18 = __sa_load_i64(__sa_ptr_add(r16, 0));
        /* no-op release: !__mpsc_recv_ok_second */
        r19 = __sa_alloc(8);
        __pc = 20; break;
      }
      case 20: {
        r20 = __mpsc_try_recv(r12, r19);
        __pc = (__sa_truthy(r20) ? 22 : 21); break;
      }
      case 21: {
        /* no-op release: !__mpsc_recv_ok_third */
        sa_time_sleep_ns(1);
        __pc = 20; break;
      }
      case 22: {
        r21 = __sa_load_i64(__sa_ptr_add(r19, 0));
        /* no-op release: !__mpsc_recv_ok_third */
        r22 = __sa_alloc(8);
        __pc = 23; break;
      }
      case 23: {
        r23 = __mpsc_try_recv(r12, r22);
        __pc = (__sa_truthy(r23) ? 25 : 24); break;
      }
      case 24: {
        /* no-op release: !__mpsc_recv_ok_fourth */
        sa_time_sleep_ns(1);
        __pc = 23; break;
      }
      case 25: {
        r24 = __sa_load_i64(__sa_ptr_add(r22, 0));
        /* no-op release: !__mpsc_recv_ok_fourth */
        r25 = __sa_eq(r15, 10);
        r26 = __sa_eq(r18, 20);
        r27 = __sa_eq(r21, 30);
        r28 = __sa_eq(r24, 40);
        r29 = __sa_band(r25, r26);
        r30 = __sa_band(r27, r28);
        r31 = __sa_band(r29, r30);
        /* no-op release: !first */
        /* no-op release: !second */
        /* no-op release: !third */
        /* no-op release: !fourth */
        /* no-op release: !ok_first */
        /* no-op release: !ok_second */
        /* no-op release: !ok_third */
        /* no-op release: !ok_fourth */
        /* no-op release: !ok12 */
        /* no-op release: !ok34 */
        __pc = (__sa_truthy(r31) ? 26 : 27); break;
      }
      case 26: {
        /* no-op release: !ok */
        /* no-op release: !chan */
        sa_print_bytes(C_RESULT_OK, 8);
        return (0);
      }
      case 27: {
        /* no-op release: !ok */
        /* no-op release: !chan */
        sa_print_bytes(C_RESULT_ERR, 6);
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}
function sa_num_add_checked() { __sa_trap("extern not linked: sa_num_add_checked"); }
function sa_num_sub_checked() { __sa_trap("extern not linked: sa_num_sub_checked"); }
function sa_num_mul_checked() { __sa_trap("extern not linked: sa_num_mul_checked"); }
function sa_time_instant_ns() { __sa_trap("extern not linked: sa_time_instant_ns"); }
function sa_time_unix_s() { __sa_trap("extern not linked: sa_time_unix_s"); }
function sa_time_unix_ms() { __sa_trap("extern not linked: sa_time_unix_ms"); }
function sa_time_unix_ns() { __sa_trap("extern not linked: sa_time_unix_ns"); }
function sa_time_utc_now() { __sa_trap("extern not linked: sa_time_utc_now"); }
function sa_time_sleep_ns() { __sa_trap("extern not linked: sa_time_sleep_ns"); }
function sa_time_sleep_ms() { __sa_trap("extern not linked: sa_time_sleep_ms"); }
function sa_time_iso_from_unix_ms() { __sa_trap("extern not linked: sa_time_iso_from_unix_ms"); }
function sa_time_parse_iso() { __sa_trap("extern not linked: sa_time_parse_iso"); }
function sa_time_get_full_year() { __sa_trap("extern not linked: sa_time_get_full_year"); }
function sa_time_get_month() { __sa_trap("extern not linked: sa_time_get_month"); }
function sa_time_get_date() { __sa_trap("extern not linked: sa_time_get_date"); }
function sa_time_get_hours() { __sa_trap("extern not linked: sa_time_get_hours"); }
function sa_time_get_minutes() { __sa_trap("extern not linked: sa_time_get_minutes"); }
function sa_time_get_seconds() { __sa_trap("extern not linked: sa_time_get_seconds"); }
function sa_time_get_milliseconds() { __sa_trap("extern not linked: sa_time_get_milliseconds"); }
function sa_time_get_day() { __sa_trap("extern not linked: sa_time_get_day"); }
function sa_time_set_field() { __sa_trap("extern not linked: sa_time_set_field"); }
function sa_time_format_utc() { __sa_trap("extern not linked: sa_time_format_utc"); }

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
