// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((size | 0), 8);
  const ptr = __sa_brk;
  __sa_brk += size;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, ptr, ptr + size);
  return ptr | 0;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), v | 0); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), v | 0); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), v | 0, true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), v | 0, true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), v | 0, true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), v >>> 0, true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a) / d); } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a) % d); } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_cvt(v) { return v; }
// ---- end runtime ----
// source: /content/sa_all/sci/demos/rosetta/53_cache_hits/main.sa
const __sa_ftable = [];
const C_RESULT_OK = 4096; // utf8 (2 bytes)
__sa_u8.set([51,10], 4096);
const C_RESULT_ERR = 4104; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4104);
export function lookup(cache_entry) {
  let r0 = 0, r1 = 0, r2 = C_RESULT_OK, r3 = C_RESULT_ERR;
  r0 = cache_entry;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r1 = __sa_load_i32(__sa_ptr_add(r0, 4));
        /* no-op release: !cache_entry */
        return (r1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
export function main() {
  let r0 = 0, r1 = 0, r2 = 0, r3 = C_RESULT_OK, r4 = C_RESULT_ERR;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = __sa_alloc(8);
        __sa_store_i32(__sa_ptr_add(r0, 0), 0);
        __sa_store_i32(__sa_ptr_add(r0, 4), 3);
        r1 = lookup(r0);
        r2 = __sa_eq(r1, 3);
        /* no-op release: !value */
        /* no-op release: !cache_entry */
        __pc = (__sa_truthy(r2) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_OK, 2);
        return (0);
      }
      case 3: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_ERR, 6);
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
