// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
const __sa_live = new Set(); // live heap bases (user pointers handed out by __sa_alloc)
const __sa_fl = Object.create(null); // free-list buckets: aligned size -> stack of user pointers
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((size | 0), 8);
  const bucket = __sa_fl[size];
  if (bucket && bucket.length) { const ptr = bucket.pop(); __sa_u8.fill(0, ptr, ptr + size); __sa_live.add(ptr | 0); return ptr | 0; }
  const total = (size + 8); // 8-byte header holds the aligned user size
  const base = __sa_brk;
  __sa_brk += total;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, base, base + total);
  __sa_view.setUint32(base, size, true);
  const ptr = (base + 8);
  __sa_live.add(ptr | 0);
  return ptr | 0;
}
function __sa_free(ptr) {
  // Mirrors the interpreter: only exact live heap bases are recycled.
  // i64 bigints, i32 values, interior pointers, consts and unknown
  // addresses are no-ops (never present in __sa_live).
  if (typeof ptr !== "number") return 0;
  const p = ptr | 0;
  if (!__sa_live.has(p)) return 0;
  __sa_live.delete(p);
  const size = __sa_view.getUint32((p - 8), true);
  (__sa_fl[size] || (__sa_fl[size] = [])).push(p);
  return 0;
}
const __sa_fstack = []; // call-stack of frames; each frame lists its stack slots
function __sa_salloc(size) {
  // Function-scoped allocation: freed when the owning frame returns
  // (mirrors stack-slot lifetime; the interpreter never frees these
  // mid-frame either). Returned to the free list on frame pop.
  const ptr = __sa_alloc(size);
  if (__sa_fstack.length) __sa_fstack[__sa_fstack.length - 1].push(ptr | 0);
  return ptr;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), v | 0); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), v | 0); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), v | 0, true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), v | 0, true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), v | 0, true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), v >>> 0, true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a) / d); } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a) % d); } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_cvt(v) { return v; }
// ---- end runtime ----
// source: /content/sa_all/sci/demos/support/sort_probe.sa
const __sa_ftable = [cmp_i32_asc];
const C_RESULT_OK = 4096; // utf8 (8 bytes)
__sa_u8.set([115,111,114,116,32,111,107,10], 4096);
const C_I32_CMP_VT = 4104; // vtable (8 bytes)
__sa_u8.set([0,0,0,0,0,0,65,83], 4104);
export function sa_mem_copy(dst, src, count) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = 0, r18 = 0, r19 = 0;
  r0 = dst;
  r1 = src;
  r2 = count;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_ne(r2, 0);
        __pc = (__sa_truthy(r3) ? 2 : 7); break;
      }
      case 2: {
        r4 = __sa_eq(r0, 0);
        __pc = (__sa_truthy(r4) ? 3 : 4); break;
      }
      case 3: {
        __sa_panic(1701);
        __pc = 4; break;
      }
      case 4: {
        r5 = __sa_eq(r1, 0);
        __pc = (__sa_truthy(r5) ? 5 : 6); break;
      }
      case 5: {
        __sa_panic(1702);
        __pc = 6; break;
      }
      case 6: {
        /* no-op release: !src_null */
        /* no-op release: !dst_null */
        __pc = 7; break;
      }
      case 7: {
        r6 = __sa_salloc(8);
        r7 = __sa_salloc(8);
        r8 = __sa_salloc(8);
        r9 = __sa_salloc(8);
        __sa_store_i64(__sa_ptr_add(r6, 0), 0);
        r10 = __sa_load_i64(__sa_ptr_add(r6, 0));
        __sa_store_i64(__sa_ptr_add(r7, 0), 1);
        r11 = __sa_load_i64(__sa_ptr_add(r7, 0));
        __sa_store_i64(__sa_ptr_add(r8, 0), 0);
        __sa_store_i64(__sa_ptr_add(r9, 0), r2);
        __pc = 8; break;
      }
      case 8: {
        r12 = __sa_load_i64(__sa_ptr_add(r8, 0));
        r13 = __sa_load_i64(__sa_ptr_add(r9, 0));
        r14 = __sa_eq(r13, r10);
        __pc = (__sa_truthy(r14) ? 10 : 9); break;
      }
      case 9: {
        r15 = __sa_ptr_add(r1, r12);
        r16 = __sa_ptr_add(r0, r12);
        r17 = __sa_load_u8(__sa_ptr_add(r15, 0));
        __sa_store_u8(__sa_ptr_add(r16, 0), r17);
        r18 = __sa_add(r12, r11);
        r19 = __sa_sub(r13, r11);
        /* no-op release: !src_ip */
        /* no-op release: !dst_ip */
        /* no-op release: !byte */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !done */
        __sa_store_i64(__sa_ptr_add(r8, 0), r18);
        __sa_store_i64(__sa_ptr_add(r9, 0), r19);
        /* no-op release: !next_offset */
        /* no-op release: !next_remaining */
        __pc = 8; break;
      }
      case 10: {
        /* no-op release: !done */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !one */
        /* no-op release: !zero */
        /* no-op release: !nonzero */
        /* no-op release: !count */
        /* no-op release: !src */
        /* no-op release: !dst */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function sa_mem_set(dst, val, count) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0;
  r0 = dst;
  r1 = val;
  r2 = count;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_ne(r2, 0);
        __pc = (__sa_truthy(r3) ? 2 : 5); break;
      }
      case 2: {
        r4 = __sa_eq(r0, 0);
        __pc = (__sa_truthy(r4) ? 3 : 4); break;
      }
      case 3: {
        __sa_panic(1703);
        __pc = 4; break;
      }
      case 4: {
        /* no-op release: !dst_null */
        __pc = 5; break;
      }
      case 5: {
        r5 = __sa_salloc(8);
        r6 = __sa_salloc(8);
        r7 = __sa_salloc(8);
        r8 = __sa_salloc(8);
        __sa_store_i64(__sa_ptr_add(r5, 0), 0);
        r9 = __sa_load_i64(__sa_ptr_add(r5, 0));
        __sa_store_i64(__sa_ptr_add(r6, 0), 1);
        r10 = __sa_load_i64(__sa_ptr_add(r6, 0));
        __sa_store_i64(__sa_ptr_add(r7, 0), 0);
        __sa_store_i64(__sa_ptr_add(r8, 0), r2);
        __pc = 6; break;
      }
      case 6: {
        r11 = __sa_load_i64(__sa_ptr_add(r7, 0));
        r12 = __sa_load_i64(__sa_ptr_add(r8, 0));
        r13 = __sa_eq(r12, r9);
        __pc = (__sa_truthy(r13) ? 8 : 7); break;
      }
      case 7: {
        r14 = __sa_ptr_add(r0, r11);
        __sa_store_u8(__sa_ptr_add(r14, 0), r1);
        r15 = __sa_add(r11, r10);
        r16 = __sa_sub(r12, r10);
        /* no-op release: !dst_ip */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !done */
        __sa_store_i64(__sa_ptr_add(r7, 0), r15);
        __sa_store_i64(__sa_ptr_add(r8, 0), r16);
        /* no-op release: !next_offset */
        /* no-op release: !next_remaining */
        __pc = 6; break;
      }
      case 8: {
        /* no-op release: !done */
        /* no-op release: !offset */
        /* no-op release: !remaining */
        /* no-op release: !one */
        /* no-op release: !zero */
        /* no-op release: !nonzero */
        /* no-op release: !count */
        /* no-op release: !val */
        /* no-op release: !dst */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function sort_swap_bytes(lhs, rhs, elem_size) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0;
  r0 = lhs;
  r1 = rhs;
  r2 = elem_size;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r3 = __sa_salloc(r2);
        sa_mem_copy(r3, r0, r2);
        sa_mem_copy(r0, r1, r2);
        sa_mem_copy(r1, r3, r2);
        /* no-op release: !lhs */
        /* no-op release: !rhs */
        /* no-op release: !elem_size */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function sort_partition_bounds(base, lo, hi, elem_size, cmp_vt) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = 0, r18 = 0, r19 = 0, r20 = 0, r21 = 0, r22 = 0, r23 = 0, r24 = 0, r25 = 0;
  r0 = base;
  r1 = lo;
  r2 = hi;
  r3 = elem_size;
  r4 = cmp_vt;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r5 = __sa_salloc(8);
        r6 = __sa_salloc(8);
        __sa_store_i64(__sa_ptr_add(r5, 0), r1);
        __sa_store_i64(__sa_ptr_add(r6, 0), r1);
        r7 = __sa_mul(r2, r3);
        r8 = __sa_ptr_add(r0, r7);
        r9 = __sa_load_i64(__sa_ptr_add(r4, 0));
        __pc = 2; break;
      }
      case 2: {
        r10 = __sa_load_i64(__sa_ptr_add(r6, 0));
        r11 = __sa_eq(r10, r2);
        __pc = (__sa_truthy(r11) ? 6 : 3); break;
      }
      case 3: {
        r12 = __sa_mul(r10, r3);
        r13 = __sa_ptr_add(r0, r12);
        r14 = __sa_call_indirect(r9, r13, r8);
        r15 = __sa_sle(r14, 0);
        __pc = (__sa_truthy(r15) ? 4 : 5); break;
      }
      case 4: {
        r16 = __sa_load_i64(__sa_ptr_add(r5, 0));
        r17 = __sa_mul(r16, r3);
        r18 = __sa_ptr_add(r0, r17);
        sort_swap_bytes(r18, r13, r3);
        r19 = __sa_add(r16, 1);
        __sa_store_i64(__sa_ptr_add(r5, 0), r19);
        r20 = __sa_add(r10, 1);
        __sa_store_i64(__sa_ptr_add(r6, 0), r20);
        /* no-op release: !done */
        /* no-op release: !i_ptr */
        /* no-op release: !i */
        /* no-op release: !i_off */
        /* no-op release: !j */
        /* no-op release: !cmp */
        /* no-op release: !should_swap */
        /* no-op release: !j_ptr */
        /* no-op release: !j_off */
        /* no-op release: !next_i */
        /* no-op release: !next_j */
        __pc = 2; break;
      }
      case 5: {
        r20 = __sa_add(r10, 1);
        __sa_store_i64(__sa_ptr_add(r6, 0), r20);
        /* no-op release: !done */
        /* no-op release: !j */
        /* no-op release: !cmp */
        /* no-op release: !should_swap */
        /* no-op release: !j_ptr */
        /* no-op release: !j_off */
        /* no-op release: !next_j */
        __pc = 2; break;
      }
      case 6: {
        r21 = __sa_load_i64(__sa_ptr_add(r5, 0));
        r22 = __sa_mul(r21, r3);
        r23 = __sa_ptr_add(r0, r22);
        r24 = __sa_mul(r2, r3);
        r25 = __sa_ptr_add(r0, r24);
        sort_swap_bytes(r23, r25, r3);
        /* no-op release: !final_pivot_ptr */
        /* no-op release: !final_pivot_off */
        /* no-op release: !end_ptr */
        /* no-op release: !end_off */
        /* no-op release: !pivot_ptr */
        /* no-op release: !pivot_off */
        /* no-op release: !base */
        /* no-op release: !lo */
        /* no-op release: !hi */
        /* no-op release: !elem_size */
        /* no-op release: !cmp_fn */
        return (r21);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function sort_qsort_bounds(base, lo, hi, elem_size, cmp_vt) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0;
  r0 = base;
  r1 = lo;
  r2 = hi;
  r3 = elem_size;
  r4 = cmp_vt;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r5 = __sa_uge(r1, r2);
        __pc = (__sa_truthy(r5) ? 9 : 2); break;
      }
      case 2: {
        r6 = sort_partition_bounds(r0, r1, r2, r3, r4);
        r7 = __sa_ugt(r6, r1);
        __pc = (__sa_truthy(r7) ? 3 : 4); break;
      }
      case 3: {
        r8 = __sa_sub(r6, 1);
        sort_qsort_bounds(r0, r1, r8, r3, r4);
        /* no-op release: !left_hi */
        /* no-op release: !has_left */
        __pc = 5; break;
      }
      case 4: {
        /* no-op release: !has_left */
        __pc = 5; break;
      }
      case 5: {
        r9 = __sa_ult(r6, r2);
        __pc = (__sa_truthy(r9) ? 6 : 7); break;
      }
      case 6: {
        r10 = __sa_add(r6, 1);
        sort_qsort_bounds(r0, r10, r2, r3, r4);
        /* no-op release: !right_lo */
        /* no-op release: !has_right */
        __pc = 8; break;
      }
      case 7: {
        /* no-op release: !has_right */
        __pc = 8; break;
      }
      case 8: {
        /* no-op release: !done */
        /* no-op release: !pivot */
        /* no-op release: !base */
        /* no-op release: !lo */
        /* no-op release: !hi */
        /* no-op release: !elem_size */
        /* no-op release: !cmp_vt */
        return 0;
      }
      case 9: {
        /* no-op release: !done */
        /* no-op release: !base */
        /* no-op release: !lo */
        /* no-op release: !hi */
        /* no-op release: !elem_size */
        /* no-op release: !cmp_vt */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function sort_qsort_len(base, len, elem_size, cmp_vt) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = C_RESULT_OK, r7 = C_I32_CMP_VT;
  r0 = base;
  r1 = len;
  r2 = elem_size;
  r3 = cmp_vt;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r4 = __sa_ule(r1, 1);
        __pc = (__sa_truthy(r4) ? 3 : 2); break;
      }
      case 2: {
        r5 = __sa_sub(r1, 1);
        sort_qsort_bounds(r0, 0, r5, r2, r3);
        /* no-op release: !last */
        /* no-op release: !short */
        __pc = 4; break;
      }
      case 3: {
        /* no-op release: !short */
        __pc = 4; break;
      }
      case 4: {
        /* no-op release: !base */
        /* no-op release: !len */
        /* no-op release: !elem_size */
        /* no-op release: !cmp_vt */
        return 0;
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function cmp_i32_asc(lhs, rhs) {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0, r6 = C_RESULT_OK, r7 = C_I32_CMP_VT;
  r0 = lhs;
  r1 = rhs;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r2 = __sa_load_i32(__sa_ptr_add(r0, 0));
        r3 = __sa_load_i32(__sa_ptr_add(r1, 0));
        r4 = __sa_slt(r2, r3);
        __pc = (__sa_truthy(r4) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !right */
        /* no-op release: !left */
        /* no-op release: !lhs */
        /* no-op release: !rhs */
        /* no-op release: !is_lt */
        return (-1);
      }
      case 3: {
        /* no-op release: !is_lt */
        r5 = __sa_sgt(r2, r3);
        __pc = (__sa_truthy(r5) ? 4 : 5); break;
      }
      case 4: {
        /* no-op release: !right */
        /* no-op release: !left */
        /* no-op release: !lhs */
        /* no-op release: !rhs */
        /* no-op release: !is_gt */
        return (1);
      }
      case 5: {
        /* no-op release: !right */
        /* no-op release: !left */
        /* no-op release: !lhs */
        /* no-op release: !rhs */
        /* no-op release: !is_gt */
        return (0);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
export function main() {
  __sa_fstack.push([]);
  try {
  let r0 = 0, r1 = 0, r2 = C_I32_CMP_VT, r3 = 0, r4 = 0, r5 = 0, r6 = 0, r7 = 0, r8 = 0, r9 = 0, r10 = 0, r11 = 0, r12 = 0, r13 = 0, r14 = 0, r15 = 0, r16 = 0, r17 = C_RESULT_OK;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        r0 = __sa_alloc(20);
        __sa_store_i32(__sa_ptr_add(r0, 0), 4);
        __sa_store_i32(__sa_ptr_add(r0, 4), 1);
        __sa_store_i32(__sa_ptr_add(r0, 8), 5);
        __sa_store_i32(__sa_ptr_add(r0, 12), 2);
        __sa_store_i32(__sa_ptr_add(r0, 16), 3);
        r1 = (r2);
        sort_qsort_len(r0, 5, 4, r1);
        r3 = __sa_load_i32(__sa_ptr_add(r0, 0));
        r4 = __sa_load_i32(__sa_ptr_add(r0, 4));
        r5 = __sa_load_i32(__sa_ptr_add(r0, 8));
        r6 = __sa_load_i32(__sa_ptr_add(r0, 12));
        r7 = __sa_load_i32(__sa_ptr_add(r0, 16));
        r8 = __sa_eq(r3, 1);
        r9 = __sa_eq(r4, 2);
        r10 = __sa_eq(r5, 3);
        r11 = __sa_eq(r6, 4);
        r12 = __sa_eq(r7, 5);
        r13 = __sa_band(r8, r9);
        r14 = __sa_band(r10, r11);
        r15 = __sa_band(r13, r14);
        r16 = __sa_band(r15, r12);
        /* no-op release: !v0 */
        /* no-op release: !v1 */
        /* no-op release: !v2 */
        /* no-op release: !v3 */
        /* no-op release: !v4 */
        /* no-op release: !ok0 */
        /* no-op release: !ok1 */
        /* no-op release: !ok2 */
        /* no-op release: !ok3 */
        /* no-op release: !ok4 */
        /* no-op release: !ok01 */
        /* no-op release: !ok23 */
        /* no-op release: !ok0123 */
        /* no-op release: !cmp_vt */
        __sa_free(r0);
        __pc = (__sa_truthy(r16) ? 2 : 3); break;
      }
      case 2: {
        /* no-op release: !ok */
        sa_print_bytes(C_RESULT_OK, 8);
        return (0);
      }
      case 3: {
        /* no-op release: !ok */
        return (1);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc, __sa_free, __sa_salloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
