const std = @import("std");

const emit_options = @import("emit_options.zig");
const inst = @import("common/instruction.zig");
const sig = @import("common/signature.zig");

pub const EmitOptions = emit_options.EmitOptions;
pub const JsEmitError = error{ Failed, InvalidOperand, UnknownFunction, UnsupportedInstruction, OutOfMemory };

pub const JsFormat = enum {
    esm,
    cjs,

    pub fn parse(text: []const u8) ?JsFormat {
        if (std.mem.eql(u8, text, "esm") or std.mem.eql(u8, text, "mjs")) return .esm;
        if (std.mem.eql(u8, text, "cjs") or std.mem.eql(u8, text, "cjs")) return .cjs;
        return null;
    }
};

pub const JsEmitOptions = struct {
    format: JsFormat = .esm,
    mem_pages: u32 = 256, // 256 * 64KiB = 16MiB initial
    debug_comments: bool = true,
};

fn jsIdent(writer: anytype, name: []const u8) !void {
    // SA names may contain characters invalid in JS; sanitize.
    if (name.len == 0) return writer.writeAll("_anon");
    var first = true;
    for (name) |c| {
        const ok = std.ascii.isAlphanumeric(c) or c == '_' or c == '$';
        if (first) {
            if (std.ascii.isAlphabetic(c) or c == '_' or c == '$') {
                try writer.writeByte(c);
            } else {
                try writer.writeAll("_");
                if (ok) try writer.writeByte(c);
            }
            first = false;
        } else {
            if (ok) try writer.writeByte(c) else try writer.writeByte('_');
        }
    }
}

fn jsFuncName(writer: anytype, name: []const u8) !void {
    // Strip surrounding quotes used by test funcs.
    var n = name;
    if (n.len >= 2 and n[0] == '"' and n[n.len - 1] == '"') n = n[1 .. n.len - 1];
    try jsIdent(writer, n);
}

fn primToJsSuffix(ty: sig.PrimType) []const u8 {
    return switch (ty) {
        .i1, .i8, .i16, .i32, .u8, .u16, .u32 => "i32",
        .i64, .u64, .ptr, .blob_handle => "i64",
        .f32, .f64 => "f64",
        else => "i32",
    };
}

fn tagToPrim(tag: u32) sig.PrimType {
    return sig.primTypeFromTag(tag) orelse .i64;
}

fn loadedPrimType(base: inst.Instruction) sig.PrimType {
    if (base.operands[3] == .ty) return tagToPrim(base.operands[3].ty);
    return .i64;
}

fn opIsFloat(kind: inst.OpKind) bool {
    return switch (kind) {
        .fadd, .fsub, .fmul, .fdiv, .fneg, .fcmp_eq, .fcmp_ne, .fcmp_lt, .fcmp_le, .fcmp_gt, .fcmp_ge => true,
        else => false,
    };
}

const FuncTask = struct {
    fsig_index: usize,
    start_idx: usize, // index of func_decl in annotated
    end_idx: usize, // exclusive
    kind: inst.InstKind,
};

fn collectFuncTasks(allocator: std.mem.Allocator, verified: anytype) ![]FuncTask {
    var tasks = std.ArrayList(FuncTask).init(allocator);
    errdefer tasks.deinit();
    var sig_index: usize = 0;
    var idx: usize = 0;
    while (idx < verified.annotated.len) : (idx += 1) {
        const k = verified.annotated[idx].base.kind;
        switch (k) {
            .func_decl, .ffi_wrapper_decl, .extern_decl, .export_decl, .test_decl => {
                sig_index += 1;
                var end = idx + 1;
                while (end < verified.annotated.len) {
                    const nk = verified.annotated[end].base.kind;
                    switch (nk) {
                        .func_decl, .ffi_wrapper_decl, .extern_decl, .export_decl, .test_decl => break,
                        else => end += 1,
                    }
                }
                try tasks.append(.{
                    .fsig_index = sig_index - 1,
                    .start_idx = idx,
                    .end_idx = end,
                    .kind = k,
                });
                idx = end - 1;
            },
            else => {},
        }
    }
    return tasks.toOwnedSlice();
}

fn writeRuntimeHeader(writer: anytype, js_opt: JsEmitOptions, size_bits: u16) !void {
    const mem_bytes: usize = @as(usize, js_opt.mem_pages) * 65536;
    try writer.print("// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.\n", .{});
    try writer.print("// size_bits={d} pages={d} ({d} bytes linear memory)\n", .{ size_bits, js_opt.mem_pages, mem_bytes });
    try writer.writeAll(
        \\// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
        \\const __SA_MEM_BYTES = __SA_MEM_BYTES_DECL__;
        \\const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
        \\const __sa_view = new DataView(__sa_memory);
        \\const __sa_u8 = new Uint8Array(__sa_memory);
        \\let __sa_brk = 65536; // bump allocator starts after reserved zero page region
        \\function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
        \\function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
        \\function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
        \\function __sa_alloc(size) {
        \\  size = __sa_align((size | 0), 8);
        \\  const ptr = __sa_brk;
        \\  __sa_brk += size;
        \\  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
        \\  __sa_u8.fill(0, ptr, ptr + size);
        \\  return ptr | 0;
        \\}
        \\function __sa_load_i32(addr) { return __sa_view.getInt32(addr | 0, true); }
        \\function __sa_load_u32(addr) { return __sa_view.getUint32(addr | 0, true); }
        \\function __sa_load_f64(addr) { return __sa_view.getFloat64(addr | 0, true); }
        \\function __sa_store_i32(addr, v) { __sa_view.setInt32(addr | 0, v | 0, true); }
        \\function __sa_store_f64(addr, v) { __sa_view.setFloat64(addr | 0, +v, true); }
        \\function __sa_load_i64(addr) { return __sa_view.getBigInt64(addr | 0, true); }
        \\function __sa_store_i64(addr, v) { __sa_view.setBigInt64(addr | 0, BigInt.asIntN(64, BigInt(v)), true); }
        \\function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
        \\function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
        \\function __sa_ptr_add(ptr, off) {
        \\  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
        \\  return (ptr + off) | 0;
        \\}
        \\function __sa_i32(v) { return v | 0; }
        \\function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
        \\function __sa_f64(v) { return +v; }
        \\// ---- end runtime ----
        \\
    );
}

fn operandToJs(writer: anytype, fsig: sig.FunctionSig, op: inst.Operand, want_i64: bool) !void {
    switch (op) {
        .reg => |r| {
            const slot = fsig.slotOf(r) orelse return JsEmitError.InvalidOperand;
            try writer.print("r{d}", .{slot});
        },
        .imm_i64, .imm_int => |v| {
            if (want_i64) try writer.print("{d}n", .{v}) else try writer.print("{d}", .{v});
        },
        .imm_u64 => |v| {
            if (want_i64) try writer.print("{d}n", .{v}) else try writer.print("{d}", .{v});
        },
        .imm_float => |v| try writer.print("{d}", .{v}),
        .symbol, .label, .func => return JsEmitError.InvalidOperand,
        .text, .native_text => |t| try writer.print("/*{s}*/0", .{t}),
        else => try writer.writeAll("0"),
    }
}

fn callArgToJs(writer: anytype, fsig: sig.FunctionSig, op: inst.Operand) !void {
    switch (op) {
        .reg => |r| {
            const slot = fsig.slotOf(r) orelse return JsEmitError.InvalidOperand;
            try writer.print("r{d}", .{slot});
        },
        .imm_i64, .imm_int => |v| try writer.print("{d}", .{v}),
        .imm_u64 => |v| try writer.print("{d}", .{v}),
        .imm_float => |v| try writer.print("{d}", .{v}),
        .text, .native_text => |t| try writer.print("/*{s}*/0", .{t}),
        else => try writer.writeAll("0"),
    }
}

// Best-effort parse of `call` raw text: `dst = call @name(args...)` or `call @name(...)`.
// Falls back to UnknownFunction so caller emits a trap stub.
fn parseCallCallee(raw: []const u8) ?[]const u8 {
    const kw = "call ";
    const at = std.mem.indexOf(u8, raw, kw) orelse return null;
    var rest = std.mem.trim(u8, raw[at + kw.len ..], " \t");
    if (rest.len == 0 or rest[0] != '@') return null;
    rest = rest[1..];
    var end: usize = 0;
    while (end < rest.len and (std.ascii.isAlphanumeric(rest[end]) or rest[end] == '_' or rest[end] == '$' or rest[end] == '.' or rest[end] == '"')) : (end += 1) {}
    if (end == 0) return null;
    return rest[0..end];
}

fn emitOpExpr(writer: anytype, fsig: sig.FunctionSig, opcode: inst.OpKind, lhs: inst.Operand, rhs: inst.Operand) !void {
    const f = opIsFloat(opcode);
    switch (opcode) {
        .add => {
            try writer.writeAll("__sa_i32(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(" + ");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")");
        },
        .sub => {
            try writer.writeAll("__sa_i32(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(" - ");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")");
        },
        .mul => {
            try writer.writeAll("Math.imul(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(", ");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")");
        },
        .sdiv, .div => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")|0) === 0 ? __sa_trap(\"div by zero\") : (Math.trunc((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") / (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0))");
        },
        .udiv => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0) === 0 ? __sa_trap(\"div by zero\") : (Math.trunc(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) / ((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0))|0))");
        },
        .srem, .rem => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") % (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .urem => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) % (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0))|0)");
        },
        .neg => {
            try writer.writeAll("(-(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll("))|0");
        },
        .@"and" => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") & (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .@"or" => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") | (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .xor => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") ^ (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .shl => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") << (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .lshr, .shr => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .ashr => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >> (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))|0");
        },
        .not => {
            try writer.writeAll("(~(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll("))|0");
        },
        .eq => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") === (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .ne => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") !== (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .slt, .lt => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(")|0) < (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")|0) ? 1 : 0)");
        },
        .sle => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(")|0) <= (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")|0) ? 1 : 0)");
        },
        .sgt, .gt => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(")|0) > (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")|0) ? 1 : 0)");
        },
        .sge => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(")|0) >= (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")|0) ? 1 : 0)");
        },
        .ult => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) < (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0) ? 1 : 0)");
        },
        .ule => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) <= (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0) ? 1 : 0)");
        },
        .ugt => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) > (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0) ? 1 : 0)");
        },
        .uge => {
            try writer.writeAll("(((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >>> 0) >= (((");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") >>> 0) ? 1 : 0)");
        },
        .fadd => {
            try writer.writeAll("((");
            _ = f;
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(" + ");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(")");
        },
        .fsub => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") - (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))");
        },
        .fmul => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") * (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))");
        },
        .fdiv => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") / (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll("))");
        },
        .fneg => {
            try writer.writeAll("(-(");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll("))");
        },
        .fcmp_eq => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") === (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .fcmp_ne => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") !== (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .fcmp_lt => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") < (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .fcmp_le => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") <= (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .fcmp_gt => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") > (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        .fcmp_ge => {
            try writer.writeAll("((");
            try callArgToJs(writer, fsig, lhs);
            try writer.writeAll(") >= (");
            try callArgToJs(writer, fsig, rhs);
            try writer.writeAll(") ? 1 : 0)");
        },
        else => {
            try writer.writeAll("__sa_trap(\"unsupported op\")");
        },
    }
}

fn emitBodyAsPcMachine(writer: anytype, allocator: std.mem.Allocator, verified: anytype, fsig: sig.FunctionSig, task: FuncTask, js_opt: JsEmitOptions) !void {
    // Map label symbol id -> pc number. Entry (before first label) is pc 0.
    var label_pc = std.AutoHashMap(u32, usize).init(allocator);
    defer label_pc.deinit();
    var pcs: usize = 1; // next free pc
    var i: usize = task.start_idx + 1;
    while (i < task.end_idx) : (i += 1) {
        const base = verified.annotated[i].base;
        if (base.kind == .label) {
            const lid: u32 = switch (base.operands[1]) {
                .label => |v| v,
                .symbol => |v| v,
                else => continue,
            };
            if (label_pc.get(lid) == null) {
                try label_pc.put(lid, pcs);
                pcs += 1;
            }
        }
    }
    // If no labels at all, emit straight-line body without pc machine.
    if (pcs == 1) {
        i = task.start_idx + 1;
        while (i < task.end_idx) : (i += 1) {
            try emitLinearInstruction(writer, verified, fsig, verified.annotated[i].base, js_opt);
        }
        return;
    }

    try writer.writeAll("  let __pc = 0;\n  while (true) {\n    switch (__pc) {\n      case 0: {\n");
    i = task.start_idx + 1;
    while (i < task.end_idx) : (i += 1) {
        const base = verified.annotated[i].base;
        if (base.kind == .label) {
            const lid: u32 = switch (base.operands[1]) {
                .label => |v| v,
                .symbol => |v| v,
                else => continue,
            };
            const npc = label_pc.get(lid) orelse continue;
            try writer.print("        break;\n      }}\n      case {d}: {{\n", .{npc});
            continue;
        }
        try emitPcInstruction(writer, verified, fsig, base, &label_pc, js_opt);
    }
    try writer.writeAll("        return __sa_trap(\"fallthrough end of function\");\n      }\n      default: return __sa_trap(\"bad pc \" + __pc);\n    }\n  }\n", .{});
}

fn emitLinearInstruction(writer: anytype, verified: anytype, fsig: sig.FunctionSig, base: inst.Instruction, js_opt: JsEmitOptions) !void {
    _ = verified;
    _ = js_opt;
    switch (base.kind) {
        .return_ => {
            switch (base.operands[0]) {
                .none => try writer.writeAll("  return 0;\n"),
                else => {
                    try writer.writeAll("  return (");
                    try callArgToJs(writer, fsig, base.operands[0]);
                    try writer.writeAll(");\n");
                },
            }
        },
        .op => {
            const dst_slot = if (base.operands[0] == .reg) (fsig.slotOf(base.operands[0].reg) orelse return JsEmitError.InvalidOperand) else return JsEmitError.InvalidOperand;
            const opcode = base.op_kind orelse return JsEmitError.InvalidOperand;
            if (inst.isTypeConversionOpKind(opcode)) {
                try writer.print("  r{d} = (", .{dst_slot});
                try callArgToJs(writer, fsig, base.operands[1]);
                try writer.writeAll(");\n");
                return;
            }
            try writer.print("  r{d} = ", .{dst_slot});
            if (opcode == .fneg) {
                try writer.writeAll("(-(");
                try callArgToJs(writer, fsig, base.operands[1]);
                try writer.writeAll("));\n");
                return;
            }
            try emitOpExpr(writer, fsig, opcode, base.operands[1], base.operands[2]);
            try writer.writeAll(";\n");
        },
        .assign => {
            const dst_slot = if (base.operands[0] == .reg) (fsig.slotOf(base.operands[0].reg) orelse return JsEmitError.InvalidOperand) else return JsEmitError.InvalidOperand;
            try writer.print("  r{d} = (", .{dst_slot});
            try callArgToJs(writer, fsig, base.operands[1]);
            try writer.writeAll(");\n");
        },
        .alloc, .stack_alloc => {
            const dst_slot = if (base.operands[0] == .reg) (fsig.slotOf(base.operands[0].reg) orelse return JsEmitError.InvalidOperand) else return JsEmitError.InvalidOperand;
            try writer.print("  r{d} = __sa_alloc(", .{dst_slot});
            try callArgToJs(writer, fsig, base.operands[1]);
            try writer.writeAll(");\n");
        },
        .ptr_add => {
            const dst_slot = if (base.operands[0] == .reg) (fsig.slotOf(base.operands[0].reg) orelse return JsEmitError.InvalidOperand) else return JsEmitError.InvalidOperand;
            try writer.print("  r{d} = __sa_ptr_add(", .{dst_slot});
            try callArgToJs(writer, fsig, base.operands[1]);
            try writer.writeAll(", ");
            try callArgToJs(writer, fsig, base.operands[2]);
            try writer.writeAll(");\n");
        },
        .load, .take => {
            const dst_slot = if (base.operands[0] == .reg) (fsig.slotOf(base.operands[0].reg) orelse return JsEmitError.InvalidOperand) else return JsEmitError.InvalidOperand;
            const ty = loadedPrimType(base);
            try writer.print("  r{d} = ", .{dst_slot});
            switch (ty) {
                .i64, .u64 => {
                    try writer.writeAll("__sa_load_i64(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll("));\n");
                },
                .f32, .f64 => {
                    try writer.writeAll("__sa_load_f64(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll("));\n");
                },
                .ptr, .blob_handle => {
                    try writer.writeAll("__sa_load_ptr(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll("));\n");
                },
                else => {
                    try writer.writeAll("__sa_load_i32(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll("));\n");
                },
            }
        },
        .store => {
            const ty = loadedPrimType(base);
            switch (ty) {
                .i64, .u64, .ptr, .blob_handle => {
                    try writer.writeAll("  __sa_store_i64(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[0]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll("), ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll(");\n");
                },
                .f32, .f64 => {
                    try writer.writeAll("  __sa_store_f64(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[0]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll("), ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll(");\n");
                },
                else => {
                    try writer.writeAll("  __sa_store_i32(__sa_ptr_add(");
                    try callArgToJs(writer, fsig, base.operands[0]);
                    try writer.writeAll(", ");
                    try callArgToJs(writer, fsig, base.operands[1]);
                    try writer.writeAll("), ");
                    try callArgToJs(writer, fsig, base.operands[2]);
                    try writer.writeAll(");\n");
                },
            }
        },
        .call, .call_indirect => {
            const callee = parseCallCallee(base.raw_text);
            if (callee) |c| {
                // dest detection: `dst = call ...` -> operands hold dest reg? raw fallback: check operands[0].
                var has_dst = false;
                var dst_slot: u32 = 0;
                if (base.operands[0] == .reg) {
                    if (fsig.slotOf(base.operands[0].reg)) |s| {
                        has_dst = true;
                        dst_slot = s;
                    }
                }
                if (has_dst) try writer.print("  r{d} = ", .{dst_slot});
                try writer.writeAll("  ");
                if (!has_dst) try writer.writeAll("  ");
                // callee name sanitized; args unknown from typed operands -> pass no args + comment.
                try writer.writeAll("__sa_call_");
                try jsIdent(writer, c);
                try writer.print(" /* {s} */", .{std.mem.trim(u8, base.raw_text, " \t\r\n")});
                try writer.writeAll(";\n");
            } else {
                try writer.print("  __sa_trap(\"unsupported call: {s}\");\n", .{std.mem.trim(u8, base.raw_text, " \t\r\n")});
            }
        },
        .panic => {
            try writer.writeAll("  __sa_panic(");
            try callArgToJs(writer, fsig, base.operands[0]);
            try writer.writeAll(");\n");
        },
        .panic_msg => {
            try writer.writeAll("  __sa_trap(\"panic_msg\");\n");
        },
        .borrow, .move_, .release, .assume_safe, .assume_borrow, .raw_cast => {
            try writer.print("  /* no-op {s}: {s} */\n", .{ @tagName(base.kind), std.mem.trim(u8, base.raw_text, " \t\r\n") });
        },
        else => {
            try writer.print("  __sa_trap(\"unsupported {s}: {s}\");\n", .{ @tagName(base.kind), std.mem.trim(u8, base.raw_text, " \t\r\n") });
        },
    }
}

fn emitPcInstruction(writer: anytype, verified: anytype, fsig: sig.FunctionSig, base: inst.Instruction, label_pc: *std.AutoHashMap(u32, usize), js_opt: JsEmitOptions) !void {
    switch (base.kind) {
        .jmp => {
            const lid: u32 = switch (base.operands[1]) {
                .label => |v| v,
                .symbol => |v| v,
                else => return JsEmitError.InvalidOperand,
            };
            const npc = label_pc.get(lid) orelse return JsEmitError.UnknownFunction;
            try writer.print("        __pc = {d}; break;\n", .{npc});
        },
        .br => {
            const cond_reg = switch (base.operands[0]) {
                .reg => |v| v,
                else => return JsEmitError.InvalidOperand,
            };
            const t: u32 = switch (base.operands[1]) {
                .label => |v| v,
                .symbol => |v| v,
                else => return JsEmitError.InvalidOperand,
            };
            const f: u32 = switch (base.operands[3]) {
                .label => |v| v,
                .symbol => |v| v,
                else => return JsEmitError.InvalidOperand,
            };
            const tpc = label_pc.get(t) orelse return JsEmitError.UnknownFunction;
            const fpc = label_pc.get(f) orelse return JsEmitError.UnknownFunction;
            const slot = fsig.slotOf(cond_reg) orelse return JsEmitError.InvalidOperand;
            try writer.print("        __pc = ((r{d}|0) !== 0) ? {d} : {d}; break;\n", .{ slot, tpc, fpc });
        },
        .return_ => {
            switch (base.operands[0]) {
                .none => try writer.writeAll("        return 0;\n"),
                else => {
                    try writer.writeAll("        return (");
                    try callArgToJs(writer, fsig, base.operands[0]);
                    try writer.writeAll(");\n");
                },
            }
        },
        else => {
            try writer.writeAll("        ");
            // reuse linear emitter but indented + no trailing pc break needed
            var buf: [8192]u8 = undefined;
            var fbs = std.io.fixedBufferStream(&buf);
            try emitLinearInstruction(fbs.writer(), verified, fsig, base, js_opt);
            const s = std.mem.trim(u8, fbs.getWritten(), " \t\r\n");
            try writer.print("{s}\n", .{s});
        },
    }
}

fn emitOneFunction(writer: anytype, allocator: std.mem.Allocator, verified: anytype, task: FuncTask, js_opt: JsEmitOptions) !void {
    const fsig = verified.function_sigs[task.fsig_index];
    if (task.kind == .extern_decl) {
        try writer.writeAll("function ");
        try jsFuncName(writer, fsig.name);
        try writer.writeAll("() { __sa_trap(\"extern not linked: ");
        try jsFuncName(writer, fsig.name);
        try writer.writeAll("\"); }\n");
        return;
    }
    if (js_opt.format == .esm) try writer.writeAll("export function ") else try writer.writeAll("function ");
    try jsFuncName(writer, fsig.name);
    try writer.writeAll("(");
    for (fsig.params, 0..) |p, idx| {
        if (idx != 0) try writer.writeAll(", ");
        try jsIdent(writer, p.name);
    }
    try writer.writeAll(") {\n");
    if (js_opt.debug_comments) {
        try writer.print("  // sa-sig: {s} -> {s} regs={d}\n", .{ fsig.name, sig.primTypeName(fsig.return_ty), fsig.reg_ids.len });
    }
    // Declare registers as locals, params take precedence for matching param reg ids.
    if (fsig.reg_ids.len > 0) {
        try writer.writeAll("  let ");
        var first = true;
        for (fsig.reg_ids, 0..) |_, slot| {
            // skip slots that alias params? MVP keeps all locals; params assigned below.
            if (!first) try writer.writeAll(", ");
            try writer.print("r{d} = 0", .{slot});
            first = false;
        }
        try writer.writeAll(";\n");
        // bind params into their slots
        for (fsig.params, 0..) |p, pidx| {
            if (pidx < fsig.param_ids.len) {
                const gid = fsig.param_ids[pidx];
                if (fsig.slotOf(gid)) |slot| {
                    try writer.print("  r{d} = ", .{slot});
                    try jsIdent(writer, p.name);
                    try writer.writeAll(";\n");
                }
            }
        }
    }
    try emitBodyAsPcMachine(writer, allocator, verified, fsig, task, js_opt);
    try writer.writeAll("}\n");
}

pub fn emitJsToString(allocator: std.mem.Allocator, verified: anytype, source_path: []const u8, size_bits: u16, js_opt: JsEmitOptions) ![]u8 {
    var out = std.ArrayList(u8).init(allocator);
    errdefer out.deinit();
    const writer = out.writer();
    try writeRuntimeHeader(writer, js_opt, size_bits);
    try writer.print("// source: {s}\n", .{source_path});
    // const decls (MVP: zero-init stubs with raw comments)
    for (verified.const_decls) |decl| {
        try writer.writeAll("const ");
        try jsIdent(writer, decl.name);
        try writer.print(" = 0; // const kind={s}\n", .{@tagName(decl.value)});
    }
    const tasks = try collectFuncTasks(allocator, verified);
    defer allocator.free(tasks);
    var has_main = false;
    for (tasks) |task| {
        if (task.kind == .extern_decl) continue;
        try emitOneFunction(writer, allocator, verified, task, js_opt);
        const fsig = verified.function_sigs[task.fsig_index];
        if (std.mem.eql(u8, fsig.name, "main")) has_main = true;
    }
    // extern stubs (so calls don't ReferenceError; they trap with name)
    for (tasks) |task| {
        if (task.kind != .extern_decl) continue;
        try emitOneFunction(writer, allocator, verified, task, js_opt);
    }
    // exports + main runner
    if (js_opt.format == .cjs) {
        try writer.writeAll("\nmodule.exports = { __sa_memory, __sa_view, __sa_u8, __sa_alloc");
        for (tasks) |task| {
            if (task.kind == .extern_decl) continue;
            const fsig = verified.function_sigs[task.fsig_index];
            try writer.writeAll(", ");
            try jsFuncName(writer, fsig.name);
        }
        try writer.writeAll(" };\n");
        if (has_main) try writer.writeAll("if (require.main === module) { main(); }\n");
    } else {
        try writer.writeAll("\nexport { __sa_memory, __sa_view, __sa_u8, __sa_alloc };\n");
        if (has_main) try writer.writeAll("if (typeof process !== \"undefined\" && process.argv && process.argv[1] && process.argv[1].endsWith(\".js\")) { try { main(); } catch (e) { console.error(e); process.exit(1); } }\n");
    }
    return out.toOwnedSlice();
}

pub fn emitJsToFile(allocator: std.mem.Allocator, verified: anytype, source_path: []const u8, size_bits: u16, js_opt: JsEmitOptions, path: []const u8) !void {
    const text = try emitJsToString(allocator, verified, source_path, size_bits, js_opt);
    defer allocator.free(text);
    // patch mem-bytes placeholder
    const mem_bytes: usize = @as(usize, js_opt.mem_pages) * 65536;
    var final = try allocator.dupe(u8, text);
    defer allocator.free(final);
    const needle = "__SA_MEM_BYTES_DECL__";
    if (std.mem.indexOf(u8, final, needle)) |pos| {
        var patched = std.ArrayList(u8).init(allocator);
        errdefer patched.deinit();
        try patched.appendSlice(final[0..pos]);
        try patched.writer().print("{d}", .{mem_bytes});
        try patched.appendSlice(final[pos + needle.len ..]);
        const owned = try patched.toOwnedSlice();
        defer allocator.free(owned);
        const dir = std.fs.path.dirname(path);
        if (dir) |d| try std.fs.cwd().makePath(d);
        const f = try std.fs.cwd().createFile(path, .{});
        defer f.close();
        try f.writeAll(owned);
        return;
    }
    const dir = std.fs.path.dirname(path);
    if (dir) |d| try std.fs.cwd().makePath(d);
    const f = try std.fs.cwd().createFile(path, .{});
    defer f.close();
    try f.writeAll(final);
}

test "js ident sanitizes names" {
    var buf: [64]u8 = undefined;
    var fbs = std.io.fixedBufferStream(&buf);
    try jsIdent(fbs.writer(), "hello-world.foo");
    try std.testing.expectEqualStrings("hello_world_foo", fbs.getWritten());
}

test "js format parses esm and cjs" {
    try std.testing.expectEqual(JsFormat.esm, JsFormat.parse("esm").?);
    try std.testing.expectEqual(JsFormat.cjs, JsFormat.parse("cjs").?);
    try std.testing.expect(JsFormat.parse("bad") == null);
}
