// Generated by `sa build-js` (js backend, MVP). DO NOT EDIT.
// size_bits=64 pages=256 (16777216 bytes linear memory)
// ---- SA JS runtime (MVP, JEV: ArrayBuffer linear memory) ----
const __SA_MEM_BYTES = 16777216;
const __sa_memory = new ArrayBuffer(__SA_MEM_BYTES);
const __sa_view = new DataView(__sa_memory);
const __sa_u8 = new Uint8Array(__sa_memory);
let __sa_brk = 65536; // bump allocator starts after reserved zero page region
const __sa_live = new Set(); // live heap bases (user pointers handed out by __sa_alloc)
const __sa_fl = Object.create(null); // free-list buckets: aligned size -> stack of user pointers
function __sa_trap(msg) { throw new Error("[sa-trap] " + msg); }
function __sa_panic(code) { throw new Error("[sa-panic] code=" + code); }
function __sa_truthy(v) { return !!v; }
const __SA_FN_BASE = 0x5341000000000000n;
function __sa_fnptr(i) { return __SA_FN_BASE + BigInt(i); }
function __sa_fnval(v) { const d = BigInt(v) - __SA_FN_BASE; return (d >= 0n && d < BigInt(__sa_ftable.length)) ? Number(d) : -1; }
function __sa_call_indirect(f, ...args) { const i = __sa_fnval(f); if (i < 0) __sa_trap("bad indirect callee"); return __sa_ftable[i](...args); }
function __sa_fok(t) { return ((t && typeof t === "object" && ("s" in t)) ? ((t.s | 0) === 0) : true); }
function __sa_fv(t) { return ((t && typeof t === "object" && ("v" in t)) ? t.v : t); }
function __sa_num(v) { return (typeof v === "bigint") ? Number(v) : (+v); }
function __sa_addr(a) { return (typeof a === "bigint") ? Number(BigInt.asUintN(32, a)) : (a | 0); }
function __sa_align(n, a) { return (n + (a - 1)) & ~(a - 1); }
function __sa_alloc(size) {
  size = __sa_align((size | 0), 8);
  const bucket = __sa_fl[size];
  if (bucket && bucket.length) { const ptr = bucket.pop(); __sa_u8.fill(0, ptr, ptr + size); __sa_live.add(ptr | 0); return ptr | 0; }
  const total = (size + 8); // 8-byte header holds the aligned user size
  const base = __sa_brk;
  __sa_brk += total;
  if (__sa_brk >= __sa_memory.byteLength) __sa_trap("out of memory (bump)");
  __sa_u8.fill(0, base, base + total);
  __sa_view.setUint32(base, size, true);
  const ptr = (base + 8);
  __sa_live.add(ptr | 0);
  return ptr | 0;
}
function __sa_free(ptr) {
  // Mirrors the interpreter: only exact live heap bases are recycled.
  // i64 bigints, i32 values, interior pointers, consts and unknown
  // addresses are no-ops (never present in __sa_live).
  if (typeof ptr !== "number") return 0;
  const p = ptr | 0;
  if (!__sa_live.has(p)) return 0;
  __sa_live.delete(p);
  const size = __sa_view.getUint32((p - 8), true);
  (__sa_fl[size] || (__sa_fl[size] = [])).push(p);
  return 0;
}
const __sa_fstack = []; // call-stack of frames; each frame lists its stack slots
function __sa_salloc(size) {
  // Function-scoped allocation: freed when the owning frame returns
  // (mirrors stack-slot lifetime; the interpreter never frees these
  // mid-frame either). Returned to the free list on frame pop.
  const ptr = __sa_alloc(size);
  if (__sa_fstack.length) __sa_fstack[__sa_fstack.length - 1].push(ptr | 0);
  return ptr;
}
function __sa_load_i8(addr) { return __sa_view.getInt8(__sa_addr(addr)); }
function __sa_load_u8(addr) { return __sa_view.getUint8(__sa_addr(addr)); }
function __sa_load_i16(addr) { return __sa_view.getInt16(__sa_addr(addr), true); }
function __sa_load_u16(addr) { return __sa_view.getUint16(__sa_addr(addr), true); }
function __sa_load_i32(addr) { return __sa_view.getInt32(__sa_addr(addr), true); }
function __sa_load_u32(addr) { return __sa_view.getUint32(__sa_addr(addr), true); }
function __sa_load_f32(addr) { return __sa_view.getFloat32(__sa_addr(addr), true); }
function __sa_load_f64(addr) { return __sa_view.getFloat64(__sa_addr(addr), true); }
function __sa_store_i8(addr, v) { __sa_view.setInt8(__sa_addr(addr), v | 0); }
function __sa_store_u8(addr, v) { __sa_view.setUint8(__sa_addr(addr), v | 0); }
function __sa_store_i16(addr, v) { __sa_view.setInt16(__sa_addr(addr), v | 0, true); }
function __sa_store_u16(addr, v) { __sa_view.setUint16(__sa_addr(addr), v | 0, true); }
function __sa_store_i32(addr, v) { __sa_view.setInt32(__sa_addr(addr), v | 0, true); }
function __sa_store_u32(addr, v) { __sa_view.setUint32(__sa_addr(addr), v >>> 0, true); }
function __sa_store_f32(addr, v) { __sa_view.setFloat32(__sa_addr(addr), +v, true); }
function __sa_store_f64(addr, v) { __sa_view.setFloat64(__sa_addr(addr), +v, true); }
function __sa_load_i64(addr) { return __sa_view.getBigInt64(__sa_addr(addr), true); }
function __sa_store_i64(addr, v) { __sa_view.setBigInt64(__sa_addr(addr), BigInt.asIntN(64, BigInt(v)), true); }
function __sa_load_ptr(addr) { return __sa_load_i64(addr); }
function __sa_store_ptr(addr, v) { __sa_store_i64(addr, v); }
function __sa_ptr_add(ptr, off) {
  if (typeof ptr === "bigint" || typeof off === "bigint") return BigInt.asIntN(64, BigInt(ptr) + BigInt(off));
  return (ptr + off) | 0;
}
function __sa_i32(v) { return v | 0; }
function __sa_i64(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_f64(v) { return +v; }
function __sa_BI(v) { return BigInt.asIntN(64, BigInt(v)); }
function __sa_BU(v) { return BigInt.asUintN(64, BigInt(v)); }
function __sa_isBI(a, b) { return typeof a === "bigint" || typeof b === "bigint"; }
function __sa_add(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) + BigInt(b)) : (((+a) + (+b)) | 0); }
function __sa_sub(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) - BigInt(b)) : (((+a) - (+b)) | 0); }
function __sa_mul(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) * BigInt(b)) : Math.imul(a, b); }
function __sa_sdiv(a, b) { if (__sa_isBI(a, b)) { if (BigInt(b) === 0n) __sa_trap("div by zero"); return __sa_BI(BigInt(a) / BigInt(b)); } if ((b | 0) === 0) __sa_trap("div by zero"); return (Math.trunc(a / b)) | 0; }
function __sa_udiv(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("div by zero"); return __sa_BU(BigInt(a) / d); } if ((b >>> 0) === 0) __sa_trap("div by zero"); return (Math.trunc((a >>> 0) / (b >>> 0))) | 0; }
function __sa_srem(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) % BigInt(b)) : ((a % b) | 0); }
function __sa_urem(a, b) { if (__sa_isBI(a, b)) { const d = __sa_BU(b); if (d === 0n) __sa_trap("rem by zero"); return __sa_BU(BigInt(a) % d); } return (((a >>> 0) % (b >>> 0)) | 0); }
function __sa_neg(a) { return (typeof a === "bigint") ? __sa_BI(-a) : ((-a) | 0); }
function __sa_band(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) & BigInt(b)) : ((a & b) | 0); }
function __sa_bor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) | BigInt(b)) : ((a | b) | 0); }
function __sa_bxor(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) ^ BigInt(b)) : ((a ^ b) | 0); }
function __sa_shl(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) << (BigInt(b) & 63n)) : ((a << (b & 31)) | 0); }
function __sa_lshr(a, b) { return __sa_isBI(a, b) ? __sa_BU(BigInt(a) >> (BigInt(b) & 63n)) : ((a >>> (b & 31)) | 0); }
function __sa_ashr(a, b) { return __sa_isBI(a, b) ? __sa_BI(BigInt(a) >> (BigInt(b) & 63n)) : ((a >> (b & 31)) | 0); }
function __sa_bnot(a) { return (typeof a === "bigint") ? __sa_BI(~a) : ((~a) | 0); }
function __sa_eq(a, b) { return ((a == b) ? 1 : 0); }
function __sa_ne(a, b) { return ((a != b) ? 1 : 0); }
function __sa_slt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) < BigInt(b)) : ((a | 0) < (b | 0))) ? 1 : 0); }
function __sa_sle(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) <= BigInt(b)) : ((a | 0) <= (b | 0))) ? 1 : 0); }
function __sa_sgt(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) > BigInt(b)) : ((a | 0) > (b | 0))) ? 1 : 0); }
function __sa_sge(a, b) { return ((__sa_isBI(a, b) ? (BigInt(a) >= BigInt(b)) : ((a | 0) >= (b | 0))) ? 1 : 0); }
function __sa_ult(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) < __sa_BU(b)) : ((a >>> 0) < (b >>> 0))) ? 1 : 0); }
function __sa_ule(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) <= __sa_BU(b)) : ((a >>> 0) <= (b >>> 0))) ? 1 : 0); }
function __sa_ugt(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) > __sa_BU(b)) : ((a >>> 0) > (b >>> 0))) ? 1 : 0); }
function __sa_uge(a, b) { return ((__sa_isBI(a, b) ? (__sa_BU(a) >= __sa_BU(b)) : ((a >>> 0) >= (b >>> 0))) ? 1 : 0); }
function __sa_fadd(a, b) { return ((+a) + (+b)); }
function __sa_fsub(a, b) { return ((+a) - (+b)); }
function __sa_fmul(a, b) { return ((+a) * (+b)); }
function __sa_fdiv(a, b) { return ((+a) / (+b)); }
function __sa_fneg(a) { return (-(+a)); }
function __sa_feq(a, b) { return (((+a) === (+b)) ? 1 : 0); }
function __sa_fne(a, b) { return (((+a) !== (+b)) ? 1 : 0); }
function __sa_flt(a, b) { return (((+a) < (+b)) ? 1 : 0); }
function __sa_fle(a, b) { return (((+a) <= (+b)) ? 1 : 0); }
function __sa_fgt(a, b) { return (((+a) > (+b)) ? 1 : 0); }
function __sa_fge(a, b) { return (((+a) >= (+b)) ? 1 : 0); }
function __sa_cvt(v) { return v; }
// ---- end runtime ----
// source: /content/sa_all/sci/demos/rosetta/200_sa_asm_quine/main.sa
const __sa_ftable = [];
const C_RESULT_ERR = 4096; // utf8 (6 bytes)
__sa_u8.set([101,114,114,111,114,10], 4096);
const C_SOURCE = 4104; // utf8 (263 bytes)
__sa_u8.set([64,105,109,112,111,114,116,32,34,115,97,95,115,116,100,47,105,111,47,112,114,105,110,116,46,115,97,105,34,10,10,64,99,111,110,115,116,32,82,69,83,85,76,84,95,69,82,82,32,61,32,117,116,102,56,58,34,101,114,114,111,114,92,110,34,10,64,99,111,110,115,116,32,83,79,85,82,67,69,32,61,32,117,116,102,56,58,34,64,105,109,112,111,114,116,32,92,34,115,97,95,115,116,100,47,105,111,47,112,114,105,110,116,46,115,97,105,92,34,92,110,92,110,64,99,111,110,115,116,32,82,69,83,85,76,84,95,69,82,82,32,61,32,117,116,102,56,58,92,34,101,114,114,111,114,92,92,110,92,34,92,110,64,99,111,110,115,116,32,83,79,85,82,67,69,32,61,32,117,116,102,56,58,34,10,10,64,109,97,105,110,40,41,32,45,62,32,105,51,50,58,10,76,95,69,78,84,82,89,58,10,32,32,32,32,99,97,108,108,32,64,115,97,95,112,114,105,110,116,95,98,121,116,101,115,40,38,83,79,85,82,67,69,44,32,50,48,48,41,10,32,32,32,32,114,101,116,117,114,110,32,48,10], 4104);
export function main() {
  __sa_fstack.push([]);
  try {
  let r0 = C_RESULT_ERR, r1 = C_SOURCE;
  let __pc = 0;
  while (true) {
    switch (__pc) {
      case 0: {
        __pc = 1; break;
      }
      case 1: {
        sa_print_bytes(C_SOURCE, 200);
        return (0);
        return __sa_trap("fallthrough end of function");
      }
      default: return __sa_trap("bad pc " + __pc);
    }
  }
  } finally { const __f = __sa_fstack.pop(); for (let __k = 0; __k < __f.length; __k++) __sa_free(__f[__k]); }
}
function sa_print_bytes(ptr, len) {
  const a = __sa_addr(ptr), n = __sa_num(len);
  const s = new globalThis.TextDecoder().decode(__sa_u8.slice(a, a + n));
  if (typeof globalThis.process !== "undefined" && globalThis.process.stdout) { globalThis.process.stdout.write(s); }
  else { globalThis.console.log(s); }
  return 0;
}

export { __sa_memory, __sa_view, __sa_u8, __sa_alloc, __sa_free, __sa_salloc };
if (typeof globalThis.process !== "undefined" && globalThis.process.argv && globalThis.process.argv[1] && /\.(mjs|js|cjs)$/.test(globalThis.process.argv[1])) { try { main(); } catch (e) { globalThis.console.error(e); globalThis.process.exit(1); } }
